### ISSUE TITLE
Render Selection Freezes 1.3.1

### ISSUE THREAD

**Issue by JRW808** [polyend/TrackerBetaTesting#1002]
Steps to reproduce:
Make a selection in pattern view
Go to Render Selection, add a custom name (with spaces), 
select Render & Load "Exporting pattern" will display and then hang/freeze at the end of the progress bar

I had to unplug the PT to restart it. This was only happening when I had the Midi Clock In and Midi Transport In set to Midi In Jack. But it was happening every time and in every project. It works fine with those Midi setting set to Internal or Off.

**Comment by JRW808** [comment]
I just installed the 1.4 beta and am having the same issue. The Render Selection only freezes when Midi Clock in is set to Midi In jack

**Comment by anemlife** [comment]
check issue #960 
similar :)

**Comment by ROM72** [comment]
Same thing for me too with the 1.4 firmware version.
https://www.dropbox.com/s/by8dslpguvbws4t/Polyend-tracker-freezing-when-render-1.4-firmware-version.mp4?dl=0

**Comment by MortalJS** [comment]
https://polyend.com/manuals/tracker/#audio-rendering

The MIDI Clock has to be set to Internal in order to render the stems/master tracks.
