### ISSUE TITLE
[1.3.1] Step FX "Random Note" does not play in scale from config menu 

### ISSUE THREAD

**Issue by x2db** [polyend/TrackerBetaTesting#1015]
Based on this video https://www.youtube.com/watch?v=1qZU6g4WxPY&t=195s
The 'n' effect (step FX) should play random notes from the global scale (one set in the config for a project). I must have tried 20 different values/scales and hear a few notes that don't belong to scale I choose.

**Comment by MortalJS** [comment]
Hi @x2db 
Can you check if the problem occurs in firmware 1.5?

**Comment by MortalJS** [comment]
No response. Closed
