### ISSUE TITLE
v1.3.1 MIDI Clock Out not in sync or consistent

### ISSUE THREAD

**Issue by lucianthorr** [polyend/TrackerBetaTesting#1057]
### Steps to reproduce

I have the Tracker's Midi Config set to USB Clock Out.  Running this into an Expert Sleeper's FH-2, with illuminated jacks so I can both hear and see the clock output compared to the pattern being played.
It appears to be off but also it varies depending on where in the beat I paused the pattern by hitting Play.  It could be mental but if a pattern was playing and I hit Play (to pause) at exactly the offbeat, then the next time I hit Play (to resume playing), the clock would be correctly on-beat.  If I did the inverse and paused exactly on the beat, the next time I hit play, the clock would be exactly on the offbeat.

### Other important information

* How often does this bug happen? (every time, often, "it only happened once")

This behavior happens every time and I have removed all dependent modules to be sure it isn't something else.

* Does this bug happen in previous firmware versions?
 I don't know.
* Does this bug happen in every project?
yes

**Comment by MortalJS** [comment]
Duplicate #1136
