### ISSUE TITLE
[1.4.1 beta] Line in Mono Left recording not summing and odd behavior 

### ISSUE THREAD

**Issue by sunfallz** [polyend/TrackerBetaTesting#1063]
Hi, 
Line in Mono left recording not summing to mono when monitoring output, still only hear Left side output. 
Not sure if this is meant to happen still, but we’re on the right track with options now.
Would love to be able to sample anything in mono with a Mono patch cable and monitor both left and right output summed. 

Also, strange behavior:
when in Mono Left mode, with source still running, click on the Config button from the Sample Recording page, 
and suddenly you hear your mono source in both left and right as if it was summed from mono. 
( BUT this would be great if it was normal)!!!! 

Exit the Config page and you’re back to only hearing the Left output again. Odd 

* How often does this bug happen? 
* Every time

* Does this bug happen in previous firmware versions? no this is beta 1.4.1

* Does this bug happen in every project?
Yes

**Comment by tfspsound** [comment]
#1026 same issue

**Comment by sunfallz** [comment]
> #1026 same issue

Have you experienced this strange behavior too:

...when in Mono Left mode, with source still running, click on the Config button from the Sample Recording page,
and suddenly you hear your mono source in both left and right as if it was summed from mono.
Exit the Config page and you’re back to only hearing the Left output again. Odd..

**Comment by MortalJS** [comment]
#1026 duplicate
