### ISSUE TITLE
Envelope delay and visuals like on Medusa.

### ISSUE THREAD

**Issue by theGh0stCat** [polyend/TrackerBetaTesting#107]
## Hi, we're excited to hear your idea!

Before you start, did you check whether your feature was already requested?
Searching might save you quite a bit of time here.

### A new feature
Addition of delay before ADSR like on Medusa. The live envelope visual would be amazing also.

**Comment by Jacknametrouble** [comment]
Thank you for your feedback. We may think of it in the future projects.
