### ISSUE TITLE
[1.4.0b1] Performance mode pattern length issue

### ISSUE THREAD

**Issue by tfspsound** [polyend/TrackerBetaTesting#1074]
I created a song where most of the patterns where 64 steps in length with the exception of 4 patterns that are 32 steps long. I hit play and went over to performance mode where the song played through fine until it reached the first 32 step long pattern which played through the 32 steps followed by another 32 steps of silence. It behaved the same way every time it reached a 32 step long pattern. 

[edit] on further investigation if I take a 64 step pattern and make it 32 steps it will play all 64 steps as if I hadn’t adjusted it. In other words I was getting 32 steps of silence before because the next 32 steps hadn’t been written. 

Is this how performance mode is intended to work now? If it is I can remove bug from this posting and suggest as a future enhancement to allow performance mode to play patterns of varied lengths.

**Comment by loktez** [comment]
When I engage a Pattern Length value in performance FX mode, regardless of the selected track (track 1 or track 4 or both for example), all other tracks are subject to the pattern length value (while they are not selected). It seems that this problem only appeared on this version 1.4.0.b1. My best

**Comment by tfspsound** [comment]
Hey @loktez I think you have discovered a separate issue with pattern length fx. The issue I’m referring to happens when you have different pattern lengths regardless of what fx used in performance mode.

**Comment by MortalJS** [comment]
Hi @tfspsound 
Can you check if the problem occurs in firmware 1.5?

**Comment by MortalJS** [comment]
No response. Closed
