### ISSUE TITLE
[1.3.1] A minor scale not correct

### ISSUE THREAD

**Issue by vanark** [polyend/TrackerBetaTesting#1084]
Selecting the fill mode, and chosing the ‘a minor’ scale, the notes that gets filled are the wrong scale. ‘A minor’ has no sharps in it.

![E94595C1-498C-4639-9823-92FCDDDB9CE5](https://user-images.githubusercontent.com/85479320/120973873-c8420800-c76f-11eb-8bac-13500f40a5d3.jpeg)
![C112BCFA-2E06-4ED9-ACA2-F794C0B320F3](https://user-images.githubusercontent.com/85479320/120973897-cd9f5280-c76f-11eb-9994-eb7f428593f7.jpeg)

**Comment by CarloAvanti** [comment]
Hi, this is not an isssue, you are not in A minor, you are still in C minor, just selecting notes between A2 and A3. To work in A minor you have to change the root note in project settings ;)

**Comment by vanark** [comment]
Thanks. But it is an issue, as the general config just mentions “Pads root note”, not root note for everything. Also, that root note should be able to be set in the fill display, as it apparently is connected to the scales you are filling.
