### ISSUE TITLE
[1.4.0b1] Corrupted Sample when powered via USB by MacBook Pro 2015

### ISSUE THREAD

**Issue by pete223** [polyend/TrackerBetaTesting#1090]
### 1. Steps to reproduce
- Plug Tracker power cable into Macbook Pro 2015
- Power on Tracker
- Observe first sample is corrupted

### 2. Steps to reproduce
- Plug Tracker power cable into USB hub
- Power on Tracker
- Observe first sample is not corrupted
- Plug USB hub into laptop
- Observe first sample has been corrupted

### Attachments and links
![IMG_20210607_130405](https://user-images.githubusercontent.com/75266552/121056249-4d540e00-c7be-11eb-99f6-4806609a0d4e.jpg)

### Other important information

* How often does this bug happen? (every time, often, "it only happened once")
Often

* Does this bug happen in previous firmware versions?
Yes

* Does this bug happen in every project?
Yes

**Comment by pete223** [comment]
Similar to https://github.com/polyend/TrackerIssues/issues/599 but with consistent steps to reproduce

**Comment by anemlife** [comment]
Just to mention I had similar issues with a poor quality hub (full plastic, etc...) at a friend's place. Every sample from the session we recorded were corrupted because of his hub. Never happened with the one I use at home (a simple 4xUSB 3.0 but more solid built). You should maybe try with another one?

**Comment by pete223** [comment]
I connected the HUB to a different non-apple laptop and had no problem so it's purely an issue with the Macbook.
Also, connecting to a newer MacBook Air, didn't present any issues.

I wonder whether it's my Mac in particular or if it's a common issue across all Macbooks of this model.

**Comment by anemlife** [comment]
I personally use a Macbook Air 13' early 2015 and no issue with my hub! Strange...

**Comment by pete223** [comment]
Ok cool, I've updated the title with the model as you're not having an issue with your Air.

Also I took a look at [this](https://www.pixelscope.de/videos/watch/6a014b7a-0006-41af-ba32-4ab1fe7cf01d) video from the comments of the linked bug #599 and he definitely plugs it into a macbook as well (could be a 2012/13 macbook pro?)

**Comment by anemlife** [comment]
Last 3 things I can think of are:

- Did you tried plugging the tracker to the usb port that is the closest to the cable on your hub? 
(in my case for example when I plugged 4 usb powered devices into my hub, my AKAI APC40 started acting buggy. Plugging it to the closest usb port made it work fine again. I believe there's some sort of power loss when plugging too much devices that require power on such hubs)

- Did you try the other USB port to plug the hub? As far as I remember these macbooks got at least 2 usb ports

- Are you using the provided usb-c cable? Had issues with some other cables (not all of them though)

Hope you can find a solution!
