### ISSUE TITLE
Config option to Retain midi channel assigned to track

### ISSUE THREAD

**Issue by sunfallz** [polyend/TrackerBetaTesting#1094]
I use 1 of my trackers exclusively for midi sequencing external synths:

Requesting that we can select an entire track & Assign the Midi Channel for the track and have said track Retain that information when moving back and forth between tracks when editing. 

Current "normal" behavior:
-enter steps as you would on track 1 and assign to midi channel 1, 
-now, move to track 2, enter steps as you would and assign to midi channel 2
-now, return to edit track 1, and enter notes on empty steps of the same track, they end up with Midi Channel 2.
-***Notice track 1 does not retain midi channel 1 as already set earlier. 
-And when you select midi ch 1 again to enter new steps on track 1, and THEN move to track 2 again, now your entering
notes on track 2 with whatever you selected for track 1 in this endless back and forth cycle.
*Essentially it's retaining track midi ch selections across track selection.  

For ease of use, it would be amazing to be able to set and forget a tracks midi channel without having to edit each steps midi channel  when you move around the pattern.

cheers

**Comment by modulationsource** [comment]
I am not sure if I understand right.
You can choose an instrument per note in the instrument column. 
(Instrument M01-M16 at the end of the sample/instrument list)
So always when you set a new note it will be set with the actual chosen instrument,
but you can change the instrument in the instrument column.

**Comment by sunfallz** [comment]
i see what you’re saying . 
what i just realized is the bug or request is different.
i’ll edit

**Comment by craighitchings** [comment]
I would also like to be able to lock instruments to tracks (and only those tracks) for improved polyphonic live playing. Say I only want to use three tracks for an instrument to lock it to being three voices –and for accidental note holds to not spill over to other neighbouring tracks but instead steal a voice on one of those locked tracks. In the current implementation of spreading extra notes over to adjacent tracks, it’s very easy to create a complete mess.

**Comment by brucegill2** [comment]
+1

**Comment by craighitchings** [comment]
Additionally locking an instrument/midi channel to one track would be great for monophonic basslines. Possibly with last note priority so new notes replace older ones rather than spreading out across other tracks.

**Comment by acidf2018** [comment]
https://github.com/polyend/TrackerIssues/issues/1031

**Comment by ROM72** [comment]
+1. It would be very helpful indeed

**Comment by clickysteve** [comment]
+1 to this.

**Comment by sunfallz** [comment]
Can we get another 👍 +1 😃

**Comment by sunfallz** [comment]
bumpsies for this critical enhancement 😄

**Comment by sunfallz** [comment]
enhance.... 💯

**Comment by Just-Peter** [comment]
+1 that would be a big midi improvement

**Comment by sunfallz** [comment]
would love to see this in the beta! who's with me ? we've got 8 participants thus far...

**Comment by sunfallz** [comment]
Can we get another 👍 +1 😃?!

**Comment by sunfallz** [comment]
bump
