### ISSUE TITLE
[1.4.0b1] Fill-note uses incorrect instrument

### ISSUE THREAD

**Issue by circumlocutory** [polyend/TrackerBetaTesting#1096]
### Steps to reproduce

Hard to track down the path for this, but it's a frequent occurrence. Perhaps add an inst choice in that note mode?

1. Shift-select a track row which has an instrument already present (say M01)
2. In Note mode, choose fill, and fill it with some set of notes
3. Observe that it fills with perhaps the last used instrument? It's hard to tell.

### Other important information

* How often does this bug happen?
Often
* Does this bug happen in previous firmware versions?
Yes
* Does this bug happen in every project?
Yes

**Comment by sunfallz** [comment]
Hi, this I believe is similar to my feature request, #1094, when you mention "the last used instrument?".
Apparently it's an actual feature of Trackers to retain the last used midi ch/inst selections when moving back and forth between tracks in edit mode. So I made it a request. 
I noticed this from the get go and thought it was a bug. Till I talked to an old school tracker user.
