### ISSUE TITLE
[1.4.0b2] Step Repeater fx in performance mode causes loud glitch sound on empty channel

### ISSUE THREAD

**Issue by trutypesounds** [polyend/TrackerBetaTesting#1111]
### Steps to reproduce

In performance mode step repeater causes a loud glitch sound on track 5, the weird thing is there is nothing going on track 5 at all. I've attached the video and the project itself.

### Attachments and links

https://user-images.githubusercontent.com/17484006/122684842-a2f1d700-d210-11eb-8849-d6add276d0a4.MOV

[trap test.zip](https://github.com/polyend/TrackerIssues/files/6682902/trap.test.zip)

### Other important information

* Does this bug happen in every project?
not sure about that, just found out this

**Comment by tfspsound** [comment]
I experienced this too but it was a while ago, and currently it seems to be ok. I’m running 1.4.1b and it doesn’t seem to happen on that, so far.

**Comment by trutypesounds** [comment]
where did u get 1.4.1b ???


> 
> 
> I experienced this too but it was a while ago, and currently it seems to be ok. I’m running 1.4.1b and it doesn’t seem to happen on that, so far.

**Comment by trutypesounds** [comment]
now this is even weirder, check the attached video - there is nothing on channels 5678 at all, but when i mute them repeater works as intended, when unmuted they produce that buzz

https://user-images.githubusercontent.com/17484006/124283381-84ff6d00-db54-11eb-9736-60cfa451aae8.MOV

here is the project itself
[techstep098.zip](https://github.com/polyend/TrackerIssues/files/6754960/techstep098.zip)

**Comment by trutypesounds** [comment]
Well, this is really annoying now, exactly step repeater messes something up here! 
As you see in the video, the first 3 channels are playing chord (wavetable instrument), 456 are TR909 drums, 78 is empty.
In performance mode channels 45678 activated, if i start playing with step repeater, the instrument which is playing the chords (on channels 123) somehow leaks into channels 7-8 and starts to play continuously thru the song.

Clearly this is a bug, as in previous videos shown above, some of the instruments starts to "leak" into empty channels when ster repeater activated in performance mode. @ambv please confirm this as a bug

https://user-images.githubusercontent.com/17484006/126994915-3bb7574c-1a84-4977-ad3a-bda3a9f0b8b3.MOV

also i've attached the project itself here
[atx-even.zip](https://github.com/polyend/TrackerIssues/files/6878463/atx-even.zip)

**Comment by trutypesounds** [comment]
why this still not a confirmed bug? @ambv @Jacknametrouble

**Comment by trutypesounds** [comment]
well, it's still here in 1.4.1b1 guys @ambv @Jacknametrouble @ziej8asek @wjakobczyk-polyend please pay some attention to this!

https://user-images.githubusercontent.com/17484006/146426037-c4273af6-43d0-4517-9274-cd879d10a750.MOV

**Comment by trutypesounds** [comment]
@piotr3500 pls

**Comment by Jacknametrouble** [comment]
@MortalJS any luck with testing this or no luck with reproducing it?

**Comment by MortalJS** [comment]
Duplicate with #1364 > Closed
