### ISSUE TITLE
[1.4.0b2] Freezes after Preview button pressed (patterns view)

### ISSUE THREAD

**Issue by PITmast** [polyend/TrackerBetaTesting#1115]
It happens only in Pattern view when Pattern number (bottom left corner) is red flashing and playback is stopped.

1. Go to Performance mode and press Play (pattern loop)
2. Stop playing still in Performance mode
3. Go to Pattern view -> Pattern number is red flashing
4. Mark anything and press Preview -> Freeze at the end

Regards
Piotr

**Comment by MortalJS** [comment]
Duplicate #1132 and #1098 
Fixed
