### ISSUE TITLE
[1.4.0b2] Inconsistent sounds on small Gate Length FX settings

### ISSUE THREAD

**Issue by callistix** [polyend/TrackerBetaTesting#1117]
### Steps to reproduce

When adding  a couple of subsequent notes with Gate Length FX with very small gate length, I get inconsistent sounds.
It sounds like sometimes the note is played, sometimes not.

### Attachments and links

[video withoud sound](http://callistix.net/public/polytracker/poly_pattern_gate.mp4)
[the sound it produces](http://callistix.net/public/polytracker/poly_pattern_gate.wav)

Please let me know if I can help to reproduce or test the issue.

**Comment by bndofc** [comment]
can confirm this, happens when sequencing midi instruments too.

**Comment by MortalJS** [comment]
Hi @callistix 

Can you attach simple project for fastest way of reacreation?
Thanks.

**Comment by MortalJS** [comment]
Closed. No response

**Comment by bndofc** [comment]
https://user-images.githubusercontent.com/80283211/155239663-f0b7f6a0-6e70-4691-8dec-caabb593b05b.mp4

hello @MortalJS, sorry for getting back a bit late, didn't have the time to test stuff out until now;

please see the attached clip, i have the exact same sequence on track 1 and 2, only difference being their gate length FX value.  if you have any value lower than 7 on the gate length, you will start having dropped out notes, as shown on track 2

**Comment by bndofc** [comment]
also, when using MIDI instruments, gate length FX (and roll FX) completely bug out when using the offset setting in the instrument parameters; please see attached vid

https://user-images.githubusercontent.com/80283211/155240812-4a63a0b4-a1bb-415e-9599-19d3919e7f65.mp4

**Comment by MortalJS** [comment]
@ziej8asek
