### ISSUE TITLE
[1.4.0b2] Line Delay and Line Reverb only work with high input volume

### ISSUE THREAD

**Issue by callistix** [polyend/TrackerBetaTesting#1119]
Line Delay and Line Reverb only work if the volume of the sound coming from Line In is somewhat high.
There seems to be a volume threshold somewhere, below that Delay and Reverb don't kick in.

I could imagine that you guys have a gate built in to switch the DSPs off to save processing power when there's no (or a low volume) input signal, but this threshold is way to high, somewhere around 50% of the Line In VU meter!

**Comment by talktogreg** [comment]
Was only minutes away from making the same report, so can CONFIRM this issue.

**Comment by PITmast** [comment]
Hi

Additionally, I've noted the only one channel it's sent to effects when stereo is selected in configuration. But it's not such a big disadvantage I think.

Regards

**Comment by joeyfivecents** [comment]
Confirming this behavior in 1.4.0b2

**Comment by trutypesounds** [comment]
was mentioned here #1109

**Comment by eingedanke** [comment]
> was mentioned here #1109

Yes, although it's not because of decay time as mentioned in #1109 but because of volume threshold IMHO. Devs should be able to confirm this.

**Comment by trutypesounds** [comment]
> > was mentioned here #1109
> 
> Yes, although it's not because of decay time as mentioned in #1109 but because of volume threshold IMHO. Devs should be able to confirm this.

yeah, agree on threshold thing

**Comment by MortalJS** [comment]
#1211 Duplicated

**Comment by joeyfivecents** [comment]
Hello. Is there any way you guys can send me the new beta firmware? Apple
lost all of my keychain info for a lot of sites including Github so I can't
log in and don't want to start a new account and Github is acting strange
so I can't see any of the info. Thanks.
