### ISSUE TITLE
[1.4.0b2] Unable to preview already loaded samples on the Sample load screen.

### ISSUE THREAD

**Issue by modmodmodmod** [polyend/TrackerBetaTesting#1122]
Please refer to the video.
[https://drive.google.com/file/d/1Jm_IpI8WXGdndb9qZbf5eGSzYHVKsphW/view?usp=sharing](https://drive.google.com/file/d/1Jm_IpI8WXGdndb9qZbf5eGSzYHVKsphW/view?usp=sharing)

・The frequency of occurrence is every time in the corresponding project.
・I can preview in other projects without any problem.
・I haven't encountered this issue in past firmware versions. may be.

**Comment by MortalJS** [comment]
Hi @modmodmodmod 

You can check if the problem still occurs in firmware 1.5.0.
