### ISSUE TITLE
[1.4 beta] single cycle waveforms cause cpu choke

### ISSUE THREAD

**Issue by prds100** [polyend/TrackerBetaTesting#1128]
Hi

Loaded some single cycle waveforms into the tracker and tried to do some polyphony using them, the tracker was really choking with audio cut outs and stutters.  This is the most recent beta.

Only happens when trying to use single cycle waveforms (so sample playback is loop) polyphonically.

**Comment by MortalJS** [comment]
Hi @prds100 

Can you attach simple project?

**Comment by MortalJS** [comment]
Closed. No response.
