### ISSUE TITLE
[Beta 1.4.02 ] Audio Editor sample playback distorts after performing normalise

### ISSUE THREAD

**Issue by bambrose** [polyend/TrackerBetaTesting#1140]
### Steps to reproduce

Import sample
Normalise at 100%
playback is distorted... yet when I import the sample into the pattern it plays fine (is not distorted)
Is linked to massive volume discrepancy between audio editor and rest of screens

**Comment by trutypesounds** [comment]
can kinda confirm this, happened to me when two notes played at once

**Comment by bambrose** [comment]
It doesn't happen with all samples.. but certainly had it on a few. Literally import.. hit a key to play back and it's distorted .,
drop an event on the timeline and hit play and it is not distorted at all

**Comment by MortalJS** [comment]
Duplicate #1267
Fixed in 1.5.0
