### ISSUE TITLE
“Bake in” play mode 

### ISSUE THREAD

**Issue by darenager** [polyend/TrackerBetaTesting#1146]
The performance function “Pattern play mode” can lead to some really great variation in track data, it would be really great to have the ability to render new track data from this, especially the C1-C20 type.

So imagine you have a track(s) selected for performance mode, you find say C5 gives a nice variation, hold performance button and option pops up to copy current pattern to new slot with the C5 modifications turned into note data for the selected tracks.

I think this would be a really nice way to come up with a bunch of variations.

**Comment by thumperjack** [comment]
that would be awesome

**Comment by Jacknametrouble** [comment]
This won't be possible. Thank you for sharing your idea.
