### ISSUE TITLE
Issue #961 still not a priority? 

### ISSUE THREAD

**Issue by Intothegroove** [polyend/TrackerBetaTesting#1155]
sequencing and sampling external synths was working perfectly till 1.3.1. Someone had raised the issue awhile ago but it hasn't been re-implemented. Will it come back? Please bring it back, thank you.

**Comment by 77377** [comment]
Agreed, Midi out is broken

**Comment by visualearner** [comment]
Midi out seems to create hanging notes 30% of the time so I can't use it. Using it with the Poly 2 also creates hanging notes and at times just nothing, no midi out at all. I'm so sad not to be able to use this as the main brain of my studio setup.

**Comment by MortalJS** [comment]
Hi @Intothegroove 
Can you check if the problem occurs in firmware 1.5?

**Comment by MortalJS** [comment]
No response. Closed
