### ISSUE TITLE
[1.3.1] cursor won't go down (see video inside)

### ISSUE THREAD

**Issue by jiabinw** [polyend/TrackerBetaTesting#1159]
### Steps to reproduce

hard to reproduce, it only happened once. please see the video for the strange behavior. 

### Attachments and links
video: 
https://drive.google.com/file/d/1tPkzquXKWG-xq9Z8-7ibD4-CM3DlRgd3/view?usp=sharing 

### Other important information

* How often does this bug happen? (every time, often, "it only happened once")
it only happened once

* Does this bug happen in previous firmware versions?
N/A. only used this version. 

* Does this bug happen in every project?
no

**Comment by MortalJS** [comment]
Hi @jiabinw,

Thank you for your feedback.

Unfortunately I cannot reproduce this problem. I tested it on the current version 1.5.0.
Many things have been improved since version 1.3.0 so I consider the topic as finished for now.
