### ISSUE TITLE
[1.4.0] Export Song Stems causing glitch on master wav file

### ISSUE THREAD

**Issue by trutypesounds** [polyend/TrackerBetaTesting#1233]
Export song stems, listen to the master output wav file, various random audio glitches at the start of the file appears (sometimes its a loud glitch click, sometimes its a crackle).

p.s.
dear Polyend, this is getting really annoying with all those bugs all over the place =/ 

* How often does this bug happen? 
always

* Does this bug happen in previous firmware versions?
not sure

* Does this bug happen in every project?
yes

**Comment by anemlife** [comment]
Same in previous versions! 

I always do another export of the master section in addition to tracks stems, it kind of works like this

**Comment by clickysteve** [comment]
Confirming this is still an issue.

It's been a known bug for some time now. Is it possible for this to be added to the roadmap to fix?

<img width="933" alt="Screen Shot 2021-09-27 at 00 22 27" src="https://user-images.githubusercontent.com/6227598/134827740-e47bdb7b-f51f-4e61-afe2-ad9c1e89a16c.png">

**Comment by clickysteve** [comment]
Noting this was reported here back in January: https://github.com/polyend/TrackerIssues/issues/697

**Comment by MortalJS** [comment]
@ambv 
Bug confirmed. 
As in the description Export Song Stems causing glitch on master wav file.

**Comment by trutypesounds** [comment]
@MortalJS @ambv bug is still here in 1.5 while using Export Song Stems - causing pop click on master file

**Comment by Jacknametrouble** [comment]
Fixed in https://github.com/polyend/TrackerBetaTesting/releases/tag/1.6.0b2
