### ISSUE TITLE
[1.4.0] Global instrument amplitude produces a click when turned all the way down

### ISSUE THREAD

**Issue by orbitfold** [polyend/TrackerBetaTesting#1234]
### Steps to reproduce

Take a short percussive sample and reduce the amplitude in instrument parameters to the lowest value. It will still produce a click during playback of that instrument. Which seems to mean that volume reduction is applied with a delay. It does not matter if you apply a volume envelope or not. So it seems the only way to correctly adjust the volume of an instrument is to destructively edit the sample or use the global mixer which is not an option for many reasons. 

### Attachments and links

Often the best way to show the problem is to record a short video,
attach the Tracker project you were working on, and provide links.

Pro-tip: You can drag and drop images and `.zip` files directly to the edit
box when writing your bug reports. Videos are too big as attachments, you
will have to use an external service for this and provide us links. Please
don't use services that delete files after short periods of time.

### Other important information

* How often does this bug happen? (every time, often, "it only happened once")
So far always
* Does this bug happen in previous firmware versions?
No
* Does this bug happen in every project?
I don't know

**Comment by k4ot** [comment]
i had this issue with a tom sample played at low volume fx, it always comes out clicky

**Comment by antf4rm** [comment]
yep, ran into this yesterday. Turned a sample all the way down but it still had an attack sound left behind.

**Comment by MortalJS** [comment]
Hi @orbitfold,

Can you uplaoad some simple project with no more than 3 samples to fast reproduce problem?

**Comment by MortalJS** [comment]
Closed. No response
