### ISSUE TITLE
pads for track selection, mute, solo

### ISSUE THREAD

**Issue by thumperjack** [polyend/TrackerBetaTesting#1301]
there are a lot of pads, I would not be sad to give up a row of 8 for instant track selection, a row of 8 for track mute, and a row of 8 for track solo, where the lights are always on and they are always right there under the left hand

how many navigation clicks would that save over the course of even a few minutes lol

**Comment by Jacknametrouble** [comment]
This is realized by the screen buttons, pads are used for different purposes. Thank you for sharing your idea.
