### ISSUE TITLE
[1.4.0] Undo in song mode not working if applied on multiple tracks and pattern

### ISSUE THREAD

**Issue by CarloAvanti** [polyend/TrackerBetaTesting#1312]
If you copy and paste multiple tracks and patterns in one time, on already used pattern and tracks, the undo command wont work… 

* How often does this bug happen? Every time

* Does this bug happen in previous firmware versions? Yes, at least 1.3.1

* Does this bug happen in every project? It happened in different projects….

**Comment by MortalJS** [comment]
Hi @CarloAvanti Can you add firmware version. Thanks

**Comment by MortalJS** [comment]
Hi @CarloAvanti 


I have checked the problem you describe.
If you copied 4 paternas at once then the tracker will paste those 4 paternas into the grid. It will do it in one operation, but physically it will make 4 operations to copy 1 pattern.

To undo you need to press undo 4 times.

This is not a bug but a feature.
