### ISSUE TITLE
Midi Pedal support

### ISSUE THREAD

**Issue by bycym** [polyend/TrackerBetaTesting#1316]
Dear developers,

I really like if I can somehow able to play, stop, loop my tracker with a midi pedal. So when I am playing on my guitar I be able to start, stop the tracker.
Is it possible to create settings for a pedal? 
Or if i send a midi cc then the tracker stops, starts, loops?

lots of thanks!

**Comment by Jacknametrouble** [comment]
As long as your MIDI pedal controller is able to send MIDI transport and certain CC's you're good to go already.
