### ISSUE TITLE
[F1.4.1] Crash on render selection with full FX1 lane

### ISSUE THREAD

**Issue by mardlib** [polyend/TrackerBetaTesting#1327]
Hi,

when i add random fx to every of 64 steps the tracker freezes right after it starts to render the file.
This also happens with a new project with only track used and one sample loaded.

here´s a video:
https://youtu.be/NDJ7kqme84o

**Comment by piotr3500** [comment]
We cannot reproduce it and the video is private - please change it to unlisted.
Thanks!

**Comment by MortalJS** [comment]
Hi @mardlib 
Unfortunately I am unable to reproduce this error. 
I have tried with various random effects. 

Get the latest beta firmware 1.5.0 b2 and let me know if you have the same effect.

**Comment by MortalJS** [comment]
Closed. no feedback
