### ISSUE TITLE
Loop Lane 

### ISSUE THREAD

**Issue by DRxZxL** [polyend/TrackerBetaTesting#1330]
Greetings. I had an idea for a feature. For people taking advantage of the line in to sample their synthesizers. I would love to see a feature where in the arrangement window as a effect maybe, where the tracker would treat the whole nominated track as a live looplane, where it records from the start of the bar to the end of the bar treating it as one sample. That way when the bar resets it could playback the sample you just recorded in a live loop lane fashion. I dont claim to know the architecture of my beloved tracker but i feel as though this would be a gamechanger of a feature and would make the tracker an even more powerful tool to jam on and come up with new ideas. 
Thank you for your time and best wishes from across the pond in the land down under. 
Justin.

**Comment by Jacknametrouble** [comment]
Hey, thank you for your feedback. This won't be possible in the current Tracker version due to the initial assumptions of the project, but maybe in the future hardware versions there will be enough resources for this.
