### ISSUE TITLE
Sample streaming from SD card?

### ISSUE THREAD

**Issue by ndguardian** [polyend/TrackerBetaTesting#1333]
## Hi, we're excited to hear your idea!

Before you start, did you check whether your feature was already requested?
Searching might save you quite a bit of time here.

Promise I checked through the issues and didn't see one like this based on searching for SD, disk, streaming, etc. If there is an open issue for that, feel free to point me to it and I'll happily chime in there.

### A new feature

I think it would be nice if the Tracker supported running samples via disk streaming instead of loading all into memory (or being able to set accordingly on a sample-by-sample basis). In theory, this could allow for significantly higher numbers of samples to be utilized in any given project, and could also give more headroom for enabling more effects and features at a time by allocating more memory to those instead of samples. 

Similar types of features have been implemented on the Synthstrom Deluge and the 1010music Blackbox. Maybe other devices as well. But I think it would be a welcome addition to the Tracker (which is an awesome device, by the way).

Have you given any thought to this?

Thanks!

**Comment by Jacknametrouble** [comment]
Yes, this would be a nice addition. Unfortunately, the current hardware with all the initial assumptions won't allow us to implement this in this version. We'll save your cool idea for future hardware versions. Thank you,
