### ISSUE TITLE
[1.5.0b2] Update failed, corrupted screen

### ISSUE THREAD

**Issue by trutypesounds** [polyend/TrackerBetaTesting#1335]
Tried to update to 1.5.0b2 - update failed.
Resetted and then this..... tried to reset several times, unpluggin usb, no luck..... 
![photo_2021-12-24_14-39-53](https://user-images.githubusercontent.com/17484006/147349113-23d7fd5a-5f59-408a-a029-fb44d25ed56a.jpg)

![photo_2021-12-24_14-36-13](https://user-images.githubusercontent.com/17484006/147348904-d807999d-7ffd-4d2c-b4f6-ddd594fee633.jpg)

**Comment by piotr3500** [comment]
Try unplugging the power, let it rest for 30 seconds and plug again.

**Comment by trutypesounds** [comment]
> Try unplugging the power, let it rest for 30 seconds and plug again.

tried to redownload the firmware and update once again - it worked, so i guess you can close this issue
