### ISSUE TITLE
[1.5.0 b1] Incorrect Fill range

### ISSUE THREAD

**Issue by b8ck8tt** [polyend/TrackerBetaTesting#1336]
1. Create a pattern that is 8 steps long
2. Shift+up on the 1st step to highlight the entire track
3. Go to FX1 and press Fill
4. Each 1, Volume, From To, 10 to 20

Expected result: the first row has value of 10, the last row has value of **20**
Observed result: the first row has value of 10, the last row has value of **21**

Notes:
Same goes for other effects and ranges. Tested on Tempo 20-40 (20-**42**) and Micro-move 66-68 (66-**69**).
The bug can be also reproduced on FX2.

**Comment by MortalJS** [comment]
Hi @b8ck8tt 
Bug confirmed.

>>> @ziej8asek

**Comment by Jacknametrouble** [comment]
Fixed in v1.5.0
