### ISSUE TITLE
[1.5.0b2] Line Input reverb/delay only works with three-note chords running out to MIDI device 

### ISSUE THREAD

**Issue by dustboxednorth** [polyend/TrackerBetaTesting#1341]
Just got my hands on your beautiful piece of kit this Christmas and I recently started sequencing my synths with it. Just a while ago, as I hooked it up to my Yamaha DX-27, I found out that the wet signal from the Line In reverb/delay only sounds off when I play a chord (triad or more). Furthermore, single notes will only be affected by the effects when they follow said triad. Despite the title of this report, this bug also affects version 1.4.0.

**To reproduce:**

- Hook up a MIDI device supporting at least three-voice polyphony to the unit
- Unmute Line In and Line Dly/Rvb in the Global Mixer
- Insert notes with your corresponding MIDI channel as the instrument

Single notes will not be affected by line input effects, but notes with MIDI chord FX and multi-track MIDI triads will be.

P.S.: had to compress the crap out of this video with H.265 for it to get below 10MB. I assume the version of QuickTime on macOS Monterey supports H.265 encoding, as the version on Catalina does not, but I digress. This is a demonstration of the aforementioned issue:
https://user-images.githubusercontent.com/56094177/147505063-a9a5d56e-b7c8-42ba-8eed-0a30a0d3d255.mp4

**Comment by MortalJS** [comment]
Hi @dustboxednorth  

This problem has already been reported twice. It has also already been forwarded to the developers' department. I will close the current thread in order not to multiply them.

Same as:
#1109
#1211
@ziej8asek
