### ISSUE TITLE
Hilight/Select Random Sample

### ISSUE THREAD

**Issue by natebluewizard** [polyend/TrackerBetaTesting#1344]
### A new feature

Would KILL to have a button on the sample loader page that randomly selects a sample from the currently viewed folder. 

UX: 
- Push the "Random Select" button
- the currently highlighted sample switches to a new random sample in the current folder.
- Highlight only, so user can still Preview & Add / Add Next as usual. 

The main benefit would be to skip around randomly through a folder of Snares or Kicks where the typical workflow might be to browse them one at a time from the top down, meaning you always hear the same ones every time you browse that folder.. you have to deliberately scan halfway down the list.. Being able to randomly jump around the list gives a bit more of a 'fun' workflow feel to the process, as surprises and hidden gems can be discovered unexpectedly.

**Comment by Jacknametrouble** [comment]
Thank you for your sharing your idea.
