### ISSUE TITLE
An option for zero-padded row numbers

### ISSUE THREAD

**Issue by dustboxednorth** [polyend/TrackerBetaTesting#1345]
As someone who comes from traditional PC-based trackers, I'm used to counting rows starting at `00` to, say, `63`. It's a tad confusing to me when I go down to what I know as row `31` and see that it's marked as 32, even if that is more sensible in the sense of human-readability.

EDIT: I am aware of the hexadecimal option, but even software trackers that have this option use padded zeroes by default.

**Comment by trutypesounds** [comment]
> As someone who comes from traditional PC-based trackers, I'm used to counting rows starting at `00` to, say, `63`. It's a tad confusing to me when I go down to what I know as row `31` and see that it's marked as 32, even if that is more sensible in the sense of human-readability.
> 
> EDIT: I am aware of the hexadecimal option, but even software trackers that have this option use padded zeroes by default.

was mentioned here #1083 and several other places, devs answer was a bit confusing and frustrating about some kind of performance issue in case implementing those

**Comment by trutypesounds** [comment]
this approach blew my mind - doing a tracker without features that made trackers famous for

**Comment by Jacknametrouble** [comment]
Polyend Tracker is based on a classic tracker idea, but it's not intended to be copying them 1:1. It's made to be accessible for people who had no previous experience with classic trackers.
