### ISSUE TITLE
SoundFont Format Support

### ISSUE THREAD

**Issue by kenzik** [polyend/TrackerBetaTesting#1346]
As I understand it, SoundFonts are just packaged wav files with meta information.

It would be pretty cool if the PT could add support for this format like other trackers.

**Comment by Jacknametrouble** [comment]
Hey, this is a cool idea. Thank you so much for sharing. Unfortunately, we won't be able to implement this to the Tracker as it is. But we'll save it for future hardware instances. Thank you!
