### ISSUE TITLE
Self-test and button/encoder test

### ISSUE THREAD

**Issue by szszoke** [polyend/TrackerBetaTesting#1348]
I am about to buy a second hand Tracker.

I could really use a self-test mode where the device could test the different internal components like the SD card, ADC/DAC chips, FM receiver.

In addition, it would be nice to have a mode where the buttons and the encoder could be tested.

I am thinking of a simple list of events:

```
Button X pressed
Button X released
Encoder turned CW
Encoder turned CCW
```

This would let me do a quick sanity check before I buy a second-hand unit.

**Comment by Jacknametrouble** [comment]
Hey, this is a cool idea. Thank you so much for sharing. Unfortunately, we won't be able to implement this to the Tracker as it is. But we'll save it for future hardware instances. Thank you!
