### ISSUE TITLE
Top 5 Feature Requests for a 2.0 Version

### ISSUE THREAD

**Issue by nitelfy2020** [polyend/TrackerBetaTesting#1352]
1. Simple Oscilator instead of sample with continuous wave shaping, folding and a option for multi voice unison with detune parameter (Saw, Triangle, Pulse, Noise)
2. More tracks
3. Chorus and Phaser effects per instrument non destructive
4. Compressor per instrument
5. Automatic zero point detection for granular and wavetable engine

Non rated:
- More sample space
- Bug fixes
- Instrument naming with preview with instrument parameters
- Pattern repeat parameter for patterns in song mode
- Folder hierarchy projects in browser/save

Please!

**Comment by Jacknametrouble** [comment]
Thank you for your feedback.
