### ISSUE TITLE
Switch of instrument automation type in Performance mode

### ISSUE THREAD

**Issue by PITmast** [polyend/TrackerBetaTesting#1358]
### A new feature
I think a possibility to switch automation type (Off, Env, LFO) in Performance Mode would be extremely useful and will increase sound and arrange expression possibilities a lot.

What do you think guys?
Is it easy to implement?

Regards
Piotr

**Comment by bambrose** [comment]
that would be massive !! great idea

**Comment by PITmast** [comment]
Here is how it can sound like:
https://mega.nz/file/KrxwHJBJ#S0jz4Qrytsue0R39blKSxRf_qUgofR4bQ2q-IqcAYOo

Regards
Piotr

**Comment by Jacknametrouble** [comment]
Hey Piotr, thank you for your feedback. This won't be possible to implement with the current hardware due to its limitations. Maybe in the future hardware iterations. Best regards.
