### ISSUE TITLE
Stereo effect for instrument (the second delay effect would be enough)

### ISSUE THREAD

**Issue by PITmast** [polyend/TrackerBetaTesting#1359]
### A new feature
Hello everyone.
Everything in the topic.

What for?
It's always so painful choice building the project - whether to keep standard delay effect, witch is great in some cases or use it to make mono instruments more stereo (with very short times).

Currently you can't have both.

Regards
Piotr

**Comment by Jacknametrouble** [comment]
Hey, thank you for your feedback. Adding more send effects won't be possible in this hardware iteration. But we'll save the hint for the future. Respectfully,
