### ISSUE TITLE
Envelope FX

### ISSUE THREAD

**Issue by shawnroos** [polyend/TrackerBetaTesting#1363]
What: The ability to affect _Attack, Decay, Release_ or _Sustain_ as a step FX
Why: will make for more expressive programming for percussion and stab type samples.

**Comment by Jacknametrouble** [comment]
Hey, thank you for your sharing your idea. Indeed, this would be a really nice addition. But the hardware resources available (or rather not really available anymore) won't allow us to add something like this to the current hardware iteration. We'll save this for the future thou! Best regards,
