### ISSUE TITLE
[1.5.0] Open/Save logic

### ISSUE THREAD

**Issue by trutypesounds** [polyend/TrackerBetaTesting#1370]
Just see the video, after working on some project i want to load another one, system now asks a lot of additional stuff and then dont load the project i wanted to load. Behavior is not like in previous firmware, it was easier, less confusing and projects were loading.

https://user-images.githubusercontent.com/17484006/150011216-15b5556f-56f2-4af2-be59-38403182d3a0.MOV

**Comment by Jacknametrouble** [comment]
Thank you for your suggestion. This is a workflow type, not a bug.

**Comment by trutypesounds** [comment]
> Thank you for your suggestion. This is a workflow type, not a bug.

kinda workflow thing, but project are not loading in the end when using open button with all those save dialogs

**Comment by Jacknametrouble** [comment]
Yeah, I took a second and third look, and you got a point. Please provide the problematic project. Does this happen on these particular projects only or on the others too? And a classic question - how is your Tracker powered?

**Comment by trutypesounds** [comment]
> Yeah, I took a second and third look, and you got a point. Please provide the problematic project. Does this happen on these particular projects only or on the others too? And a classic question - how is your Tracker powered?

it happens with any projects (clearly visible in the video attached, tried to open any project it goes into many save dialogs and then nothing happens), tracker is powered via polyend cable & adapter

**Comment by MortalJS** [comment]
Hi @trutypesounds 

I approve this problem as a bug.

Method of restoration:
As in the video

>@ziej8asek

**Comment by Jacknametrouble** [comment]
Fixed in https://github.com/polyend/TrackerBetaTesting/releases/tag/1.6.0b2
