### ISSUE TITLE
Listen to pattern while sampling line input!

### ISSUE THREAD

**Issue by Goldfasan** [polyend/TrackerBetaTesting#1371]
Sample (record) audio that is being sent through the line input while simultaneously listening to the playing pattern.
This feature would greatly improve the workflow. You'd be able to immediately hear the sample in its intended sound environment.

Make this come true, for the ultimate sampling experience.

One could make a beat and then record his violin playing in time with the beat, or in tune with a melody.

Thank You

**Comment by Jacknametrouble** [comment]
Thank you for your feedback. This won't be possible in this hardware version due to the initial assumptions. Best,
