### ISSUE TITLE
[1.5.0] Beat slice mode : last slice plays on every inactive pad of the grid

### ISSUE THREAD

**Issue by tomasoma** [polyend/TrackerBetaTesting#1373]
### Hi, thanks for 1.5.0

this is a minor non blocking thing, perhaps you won't even call it a bug.

with a pti, with a recorded sample, then in a new project with another recorded sample, with beat sliced instrument : the last slice plays on every inactive pad of the grid, it is a bit disturbing, i didn't noticed it in 1.4.0

#### Steps to reproduce

Make or load a beat sliced instrument, then go in the pattern mode, select this instrument and play the pads

#### Other important information

* How often does this bug happen? every time

* Does this bug happen in previous firmware versions?  i didn't noticed it in 1.4.0

* Does this bug happen in every project? YES

**Comment by Jacknametrouble** [comment]
This is not a bug, it's a feature.
