### ISSUE TITLE
Noises/ Glitches while droning with wavetables

### ISSUE THREAD

**Issue by Resident-X-D** [polyend/TrackerBetaTesting#1374]
So, I’m not sure if this is a bug or something that can’t be fixed, because just of frequencies overlapping or something like that; I’m also not sure if I possibly somehow "broke" the audio engine by overdriving it or something (but it still seems like other projects are playing quite normal), or if this is something that occured with the latest firmware update, as this problem just started to appear these days (I just updated to 1.5.0),which may just be a coincidence, but we need to talk about it:

I sometimes use the Tracker as a drone instrument.
See Stazma’s Video for something similar: https://youtu.be/QNL_eseDGSI

I have multiple tracks of different wavetables playing the same note.

When several tracks are playing the same note with different waves tables and I increase the volume of some (to somwhere in the middle oft he scale, not even to the top), there seems to be some sort of problematic spot, from where a loud rhythmic crack appears in a very straight-forward manner.
You can also see it in the master menu, frequently hitting out in the Line-In-Scale, although there’s nothing connected to the line-in and even if muted.

I alreaady reduced volumes on instruments and in the master, shut down reverb and delay effects, set limieters and so on and so on…. These problems don’t go away. 
You have three or four  wavestables playing together, all in the green to yellow area of the volume spectrum, at one point cracks or gliches appear.

And at one point a rhytmic crack even appeared just playing one wavetable, I’ve attached a recording of it (flac).
[tracker-drone-recording.zip](https://github.com/polyend/TrackerBetaTesting/files/7912285/tracker-drone-recording.zip)

I'm also adding the project (folder).
Ignore the looped sound in track 8, it’s about the wavetables in tracks 1-6
[drone.zip](https://github.com/polyend/TrackerBetaTesting/files/7912260/drone.zip)

**Comment by MortalJS** [comment]
Hi @Resident-X-D 

I opened your project file.
I am not able to get the glitches you present in your recording.
In some unfavorable positions I managed to get a glitch effect but it is not unusual.
Try to read a little about wavetable, interpolation. In Traker you will also find WT smoother in the sample editor option. Read exactly what it is used for.
