### ISSUE TITLE
[1.5.0] Tracker locks up importing mod file saved from older firmware

### ISSUE THREAD

**Issue by r4dian** [polyend/TrackerBetaTesting#1377]
### Steps to reproduce

- Using firmware 1.3.1
- Export the song "Sam Slater - To Know a Vale", which was included with the tracker, as an .it
- Try and import the mod
- Tracker crashes on loading bar

### Attachments and links

( file attatched )
[Sam Slater - To Know a Vale.zip](https://github.com/polyend/TrackerBetaTesting/files/7928905/Sam.Slater.-.To.Know.a.Vale.zip)

### Other important information

Happens every time on the Tracker.

OpenMPT loads it - though it does not play back in tune, the samples after instrument 15 seem to be corrupted.

The same song exported from 1.5.0 loads.

**Comment by MortalJS** [comment]
Hey, It’s good to hear from you. Thank you for your feedback.

I don’t really think that accomplishing full compatibility in terms of exports (and imports) would be ever possible. Even with considering a standardised level of compatibility, we won’t ever be able to convert or provide data to convert our projects one to one. There’s a variety of tracker applications out there, working on a different basis and that’s also why we have to limit the import/export capabilities to the currently supported parameters and values.

The same applies to the other threads relating to .it
