### ISSUE TITLE
Etch-a-sketch waveform illustrator

### ISSUE THREAD

**Issue by tfspsound** [polyend/TrackerBetaTesting#1382]
Using the jog wheel to move the ‘pen’ and holding the direction buttons to control the direction of movement as a way to draw single cycle waveforms or wave tables. 
Maybe screen button options could be things like Pen Up/Down (whether the pen draws or not, a toggle button) Resolution, Point Add/Subtract, Point Select (move the pen without drawing then set a ‘point’ connected to the last point to create vector styled curves and straight lines) Curve (increase / decrease the radius at the peak and trough points) Erase (holding whilst moving back with the jog wheel scrubs out whatever has been drawn, maybe left arrow could do the same?) 
You could mix up vector curves with freehand lines to create who knows what. Maybe useful for when you want to do music but you’ve hit a brick wall. 
Anyway just a thought.

**Comment by Jacknametrouble** [comment]
Thank you for sharing your idea, but this isn't anything we'll be implementing to the Tracker at this point. Respectfully,
