### ISSUE TITLE
Headphone out works for headphones but not audio interface

### ISSUE THREAD

**Issue by moshier1** [polyend/TrackerBetaTesting#1384]
If I fully plug in a cable to the headphone jack the sound is incredibly grainy(works fine on headphones). To get it to work I need to leave the cable half unplugged...

**Comment by Jacknametrouble** [comment]
Please try using other audio cables.

**Comment by moshier1** [comment]
I've tried various cables, it seems to only do it on projects with many sounds and effects playing at once. It is reproducible with the just numbers demosong. I'll open a ticket on the site.
