### ISSUE TITLE
Backup/duplicate project

### ISSUE THREAD

**Issue by Raadiolained** [polyend/TrackerBetaTesting#1388]
I would like to create alternate versions of my project(s), and perhaps backup. So far I need to go to computer and manually copy-paste the project file every time I need a duplicate/backup. It would be neat if I could just do this on the device. There are even 3 button slots empty on the File page...

**Comment by Jacknametrouble** [comment]
From the instrument's level. Open your desired project > Save it as (your backup). Voila.
