### ISSUE TITLE
Screen too bright even with the lowest setting

### ISSUE THREAD

**Issue by Raadiolained** [polyend/TrackerBetaTesting#1389]
I would like the screen to be even dimmer, or perhaps just change the interface colours darker. The contrast often hurts my eyes even with the lowest setting.

**Comment by Jacknametrouble** [comment]
Thank you for your feedback. The backlight Is fixed in this case, probably not a subject for dimming it down anymore. We're working on a high contrast interface, but this will be probably opposite to what you're thinking off. Best,
