### ISSUE TITLE
[1.5.0] Parentheses as first character in folder title messes with folder navigation

### ISSUE THREAD

**Issue by Dstsckr** [polyend/TrackerBetaTesting#1396]
Using an open parentheses "(" as the first character of a folder name messes with folder navigation.

I have the following folder structure:
Samples / Wavetables / Wave Edit / (loop) /

Going into the Wave Edit folder shows the "(loop)" folder above the "/.." line.
If I try to open the (loop) folder it instead goes one folder up, back to the Wave Edit folder.
From there I can never get back out, trying to use /.. jumps back and forth between Wavetables and Wave Edit folders. 

https://youtu.be/939iXbKeSBI

Firmware is 1.5.0, have not tested on other versions.
Restarting the device resets the Sample Loader to the root folder.
Problem happens in every project, can be solved by not having parenthesis as the first sign in a folder name.
Also tried this with different folder names after the  "(", with similar result. Have not tried with other non-alphabet characters.

**Comment by MortalJS** [comment]
Hi @Dstsckr 

This case is already on the list. Therefore, I am closing as a duplicate. 
Duplicate #148
