### ISSUE TITLE
[1.5.0] Midi Instrument label shows M0 instead of M01 in Horizontal 

### ISSUE THREAD

**Issue by teknobryan** [polyend/TrackerBetaTesting#1399]
### Steps to reproduce

Put in Horizontal mode.

In Pattern Mode it shows M0 instead of M01 or M02, etc.  

### Other important information

* How often does this bug happen? Every time

* Does this bug happen in previous firmware versions?  I don't know

* Does this bug happen in every project?  Yes

**Comment by MortalJS** [comment]
Bug confirmed.
@ziej8asek

**Comment by Jacknametrouble** [comment]
Fixed in https://github.com/polyend/TrackerBetaTesting/releases/tag/1.6.0b2
