### ISSUE TITLE
1.5 No audio in Sample Editor

### ISSUE THREAD

**Issue by HeyheyMrG** [polyend/TrackerBetaTesting#1400]
In Sample Editor I get no audio when playing back a sample in a particular project.  I can see the sample play/track across but no audio - But if I press 3 or sometimes 2 pads together it will playback.  Audio otherwise is fine when previewing/editing sounds/samples - Sample Playback, Instrument Parameters etc.

This only occurs in a particular project. A new project is fine when starting from scratch

Video: (sorry - shot on phone with low audio level)

https://we.tl/t-rLuC6oJvmY

I will attempt to export the project file asap and attach here (new to the tracker)

Firmware was updated recently to 1.5

I have tried several PSUs and a new USB Power cable

**Comment by HeyheyMrG** [comment]
Yesterday I deleted the instruments in this particular project one by one and each time I deleted one I checked to see if the problem still existed, which it did.  I then did a test sample recording of some radio noise in the same project and the problem had stopped.

**Comment by UnorthodoxPark** [comment]
It also happens to me with certein samples, not all. I still have no clue why or how. Prolly the same bug.

Do you see a correct behavior of the timeline in this window? I mean, for me, sometimes the red cursor just stays frozen at 0 second, even when I hear the sample. Other times it shows perfectly advancing thru the timeline.

**Comment by HeyheyMrG** [comment]
The red cursor doesnt move when the sound plays in this particular project, you can see it in the video I made, so possibly a similar issue?? Anyway I'll double check that all volumes are set correctly, I thought I'd done this but you never know.  I'll do some more testing - thx anyway.

**Comment by HeyheyMrG** [comment]
Couldnt re create on any other projects, but still has the error if i re-load the old project.
