### ISSUE TITLE
"tune" for midi notes in performance mode?

### ISSUE THREAD

**Issue by Resident-X-D** [polyend/TrackerBetaTesting#1401]
I have a suggestion:
Could it be possible, that in performance mode, when you apply the " tune" effect to a track (note up or down), that this could also affect tracks, which send out midi (to a synth or something)? 
Or implement the midi equivalent of that into the effects which can be used in performance mode?

**Comment by bndofc** [comment]
what firmware are you on? i'm pretty sure this has been a thing since 1.4.0

**Comment by Jacknametrouble** [comment]
https://github.com/polyend/TrackerBetaTesting/releases/tag/1.4.0

"Tune" FX in performance mode now also works for MIDI notes,

**Comment by Resident-X-D** [comment]
Just found out the problem was the connected hardware devise. You can't "slide" rompler sounds while they're playing, just on the hit.
