### ISSUE TITLE
[1.5] Navigation keys and jog wheel does not respond after pushing 'Preview' (Tracker as a MIDI Slave)

### ISSUE THREAD

**Issue by UnorthodoxPark** [polyend/TrackerBetaTesting#1409]
Steps to reproduce; 

1. Set your Tracker as a MIDI slave (in my case Digitone is Master). 

2. On sequencer window, stop the reproduction, push the 'Preview' button on any step (empty or not) and then try to navigate UP and Down thru the sequencer, you should notice it does not respond to them. Not happening the same with Left and Right buttons, that works just fine.

3. The problem get solved by pushing the Play button on the MIDI master device, or on the own Tracker.

IMPORTANT, in edit mode (rec/red) all navigation keys works fine even after pushing Preview. Try this only on 'Green' mode.

It happens every time and on every project.

**Comment by MortalJS** [comment]
Bug confirmed.
@ziej8asek
