### ISSUE TITLE
Remove song mode play pattern / play song buttons extra option below screen 

### ISSUE THREAD

**Issue by laxmodin** [polyend/TrackerBetaTesting#1414]
UI suggestions

When in song mode: i don't see why there is a need for a second play button, the one that is below the screen. I think it makes a confusing user experience when you can press play from two places. Its enough with this: 

play = plays song
shift + play = repeat pattern

**Comment by Jacknametrouble** [comment]
Thank you for your feedback. This will sta as it is.
