### ISSUE TITLE
[1.5.0] Hexadecimal mode inconsistencies

### ISSUE THREAD

**Issue by teknobryan** [polyend/TrackerBetaTesting#1421]
### Steps to reproduce

Set to Hexadecimal mode in Config

Go to Perfom and the Pattern displayed is still in decimal.  This makes it confusing since "13" in hex is equal to "19" in decimal.  

Every screen should show Hex when in Hex.

**Comment by teknobryan** [comment]
to add to this, when in Hexadecimal mode, the Pattern top info is off by 1.  For example when on step 00, the top info says "Pxx.01" instead of "Pxx.00"

**Comment by Jacknametrouble** [comment]
Fixed in https://github.com/polyend/TrackerBetaTesting/releases/tag/1.6.0b2
