### ISSUE TITLE
Playback not working. v1.5 and v1.3 

### ISSUE THREAD

**Issue by myfriendscallmeJackie** [polyend/TrackerBetaTesting#1422]
Hello-

My Play button functions but only the first line of any given pattern is played. Same in song mode. The clock at the top continues to run, but the screen does not scroll. Often the first line of any given selection is the only thing able to be previewed, often not able to be previewed at all. Playback in the sample editor does not function.

My up and down arrow keys only function in rec mode or while navigating menus.

Obviously, this renders the product useless so any advice helps.

(I've hard rebooted, changed firmware)

**Comment by 0x0zzz** [comment]
Have you changed the MIDI clock-in setting?  This sounds like the behavior when you press play while it's not master (clock-in set to USB or MIDI).

**Comment by myfriendscallmeJackie** [comment]
You are the best!

And I feel like an idiot... ha. 

Thank you very much.
