### ISSUE TITLE
Option to start the decimal row numbering at "00"

### ISSUE THREAD

**Issue by koblue** [polyend/TrackerBetaTesting#1438]
Its a really minor thing, but all the old trackers started at 00 for row numbers in decimal and hex. 

That way, in 4/4 time each bar starts at 16, 32, 48 etc, not 17, 33, 49. 

Having been a hardcore FastTracker 2 user back in the day I keep overshooting rows by 1 out of habit. 

Unrelated: this is the best bit of kit I've had my hands on since my red/blue EMX's. Absolutely adore it.

**Comment by pcjoppe** [comment]
+1 I would love that option.

**Comment by SandyMental** [comment]
been asked a hundred times, yet they dont seem to bother instead implenting stuff no one asked for (e.g. a "new" font)

**Comment by Jacknametrouble** [comment]
Thank you for your feedback.
