### ISSUE TITLE
[v1.6.0beta1] "Pattern top info" Pattern is off by 1 when in Hex mode

### ISSUE THREAD

**Issue by teknobryan** [polyend/TrackerBetaTesting#1439]
While in Hexadecimal mode, the Pattern top info, while it is Hex, it is off by 1. For example when on step 00, the top info says "Pxx.01" instead of "Pxx.00"

**Comment by Jacknametrouble** [comment]
Fixed in https://github.com/polyend/TrackerBetaTesting/releases/tag/1.6.0b2
