### ISSUE TITLE
[1.5.0] Can't enter directory starting with special character

### ISSUE THREAD

**Issue by 0x7CA** [polyend/TrackerBetaTesting#1441]
### Steps to reproduce

In sample loader list a directory that starts with `$`, then try to enter the directory. It will go to the parent directory instead of entering the directory.
Does not have exactly the same behaviour as entering `/..`, the cursor will stay on the directory that it traversed from, while `/..` resets the cursor to the top.

I tried it with the characters `$` and `&`, but I assume it's all special characters that get indexed before `/..`

![image](https://user-images.githubusercontent.com/12113428/160256016-45739654-5442-4034-8078-c1cb3e798df7.png)
'
Upon further inspection you can't even leave the parent's folder after you get kicked out from it, neither with the special char directory or `/..`, you'll just have to reboot the tracker in order to get normal functionality on the directory up `/..` back

**Comment by 0x7CA** [comment]
Also present in 1.6.0beta1

**Comment by Jacknametrouble** [comment]
Thank you for your feedback. Special characters are not supported by the Tracker.
