### ISSUE TITLE
[v1.5.0] Volume FX Delayed/Clicking

### ISSUE THREAD

**Issue by bigsnake09** [polyend/TrackerBetaTesting#1442]
This might be related to #944 but it seems different enough to warrant its own ticket.

The volume FX has a small delay which causes audible clicks any time you switch from a high to lower volume.

### Steps to reproduce

It's easy to come across this with any kind of setup but for a clinical way to reproduce:
* Setup an instrument with a noisy sample. White noise is best to easily observe the behaviour
* Set a patterns length to 2 steps
* Create a note on both steps
* Set one of the FX columns to volume
* Set the first steps FX volume to 100
* Set the second steps FX volume to 10
* Play the pattern and record the output

For visual reference, the pattern I used to test this is:

```
1    C5 01 v100 ----
2    C5 01 v 10 ----
```

### Attachments and links

Waveform of a recording following the steps above, normalized to better show the problem. The 1st step starts off quiet before jumping to the new volume. The 2nd step starts off loud before jumping to the new volume.
![image](https://user-images.githubusercontent.com/906062/160258161-0e4baee5-ae1e-41db-88d6-133d24681ffb.png)

White noise with kickdrum to verify timing:
![image](https://user-images.githubusercontent.com/906062/160258533-00302b0e-6a69-49fe-b220-5f8e3faa361f.png)

This has a noticable impact in real world situations which is how I discovered this. Here's the waveform of a pattern switching between a kick and hats on a track I'm working on (the hats have the volume FX applied). It's most visible in the first hat, which has a loud transient.

![image](https://user-images.githubusercontent.com/906062/160258149-5e1b6190-4ef0-4c52-9776-8bf0a9adcf54.png)

### Other important information

* Tested with firmware version 1.5.0 which was preinstalled on my unit and a downloaded version of 1.5.0.
* Recorded waveforms were tested with both the stems export feature and live recording out of the trackers output jack.

**Comment by notaprogrammer9** [comment]
This didn’t happen in 1.3.0 and it is so annoying that I need to revert back to 1.3.0.
