### ISSUE TITLE
1.6.0 beta 1 - Can't change CCs on MIDI instruments

### ISSUE THREAD

**Issue by cooptrol** [polyend/TrackerBetaTesting#1450]
Restarted, loaded different projects, I cant modify the CCs assigned to ABCDEF, nor with the jogwheel nor with the arrows. If I press Delete the CC resets to 1 ModWh, and still can't be changed. 

* Does this bug happen in previous firmware versions? NO

* Does this bug happen in every project? YES

**Comment by Jacknametrouble** [comment]
Duplicate of #1433
