### ISSUE TITLE
1.6.b1 grey rectangle on the import screen 

### ISSUE THREAD

**Issue by Era63** [polyend/TrackerBetaTesting#1461]
Another possible bug

when using the import function in order to select a section of a long sample to import a grey rectangle appears in the centre of the scree thus blinding part of it.

**Comment by trutypesounds** [comment]
> Another possible bug
> 
> when using the import function in order to select a section of a long sample to import a grey rectangle appears in the centre of the scree thus blinding part of it.

already mentioned in #1431

**Comment by Era63** [comment]
ok. thanks
