### ISSUE TITLE
Option to present envelopes using X-y graph format

### ISSUE THREAD

**Issue by BigNoseChimp** [polyend/TrackerBetaTesting#1470]
![A49F8173-8A53-463A-B2A8-704F07B755AF](https://user-images.githubusercontent.com/1255367/164916805-4b811308-3da5-4b99-b891-ec67a406bb12.jpeg)
Hi!

Whenever I modify an envelope in the tracker, part of my brain tries to translate the bar-graph format into the more common X-y graph format, so I can understand them.

Would it be possible to have the option to present envelopes In the more common X-y graph format?

(Image copied from google search)

Many thanks.

**Comment by Jacknametrouble** [comment]
Thank you for your feedback.
