### ISSUE TITLE
Linking Envelope to LFO

### ISSUE THREAD

**Issue by Aisjam** [polyend/TrackerBetaTesting#1472]
## Idea
I would like a feature to connect the envelope's output amount to control the LFO's amount to create a complex LFO. 

lfoOutput = lfoAmount * envelopeAmount 

## Why
Being able to control the LFO like this would making delays for vibrato and pitch bends in and out. It would be cool to take the instrument further.

**Comment by Jacknametrouble** [comment]
Thank you for sharing your idea Jamie.
