### ISSUE TITLE
[1.6.0b2] Jog wheel software issue

### ISSUE THREAD

**Issue by PITmast** [polyend/TrackerBetaTesting#1476]
Guys,

Please check Jog wheel turn left slowly click-by-click in project list or in pattern view for instance.
It's no encoder hardware issue. It never happened with previous firmwares.

It's hard to comment.

regards
Piotr

**Comment by Synthdawg** [comment]
Seeing same thing. Rotating counter clockwise has inconsistent clicks per step change. Clockwise ok, 1 step per click.

**Comment by PRAYTHEPO** [comment]
Counter-clockwise not consistent. Clockwise is ok

**Comment by Jacknametrouble** [comment]
@PITmast nice catch, fix coming in a moment. Thank you!

**Comment by bambrose** [comment]
Yeah good spot. This is across all parameters as far as I can see (I.e even on stuff like panning / volume etc)
No counter clockwise functionality is correct 
Thank goodness someone else noticed this… it would have driven me crazy trying to work out what was wrong

**Comment by Jacknametrouble** [comment]
Fixed in https://github.com/polyend/TrackerBetaTesting/releases/tag/1.6.0b3

**Comment by bambrose** [comment]
Bloody he’ll that was quick. Polyend never sleeps obviously 
Nice one ☝️
