### ISSUE TITLE
[1.6.0b3] Export Samples - Tracker Freeze

### ISSUE THREAD

**Issue by Synthdawg** [polyend/TrackerBetaTesting#1478]
Export Samples

In the 'File' Menu the new Export Samples option locks Tracker. Page is blank with header and screen buttons only. Press 'Cancel' has no affect. Issue is repeatible.

Needs reset process to recover.

**Comment by PRAYTHEPO** [comment]
@Jacknametrouble 
The same thing happened to me also

https://user-images.githubusercontent.com/58429366/166112916-1380fd6c-40c5-4809-8867-94ba5f9da39c.MOV

**Comment by trutypesounds** [comment]
its the same here

**Comment by natct10** [comment]
Hi, I am facing the exact same behaviour with 1.6.0b4, maybe #1512 should be reopened?

**Comment by natct10** [comment]
I can confirm that this issue is solved! Thank you guys!
