### ISSUE TITLE
Tracking line in Song mode disappear until pattern ends after going to Performance mode [1.6.0b3]

### ISSUE THREAD

**Issue by PRAYTHEPO** [polyend/TrackerBetaTesting#1479]
As next pattern slot comes in, line appears again.

https://user-images.githubusercontent.com/58429366/166113078-f00d93b5-0cc9-42cb-83ce-8fa1d1419d0c.MOV

**Comment by Jacknametrouble** [comment]
Fixed in https://github.com/polyend/TrackerBetaTesting/releases/tag/1.6.0b4
