### ISSUE TITLE
Double tap to toggle Step Jump value 

### ISSUE THREAD

**Issue by chris-roerig** [polyend/TrackerBetaTesting#1483]
> Before you start, did you check whether your feature was already requested?

Yes

### A new feature

The workflow could be sped up dramatically by adding "double tap" to the Step Jump button to toggle between the current value and 0. This would be very helpful when wanting to delete individual notes without having to perform multiple "clicks" to set Step Jump to 0 and then back to whatever value you had it at. 

An enhancement on this feature (but not the MVP for me) would be for the double tap to toggle between the previous 2 settings. What I mean by this is, lets say I set Step Jump to "1" and then later I change it to "4". If I double tap Step Jump the setting will be switched to 1 and if I double tap again it will switch back to 4. To keep the spirit of the original request, maybe a "triple tap" could default to 0..

**Comment by Jacknametrouble** [comment]
Thank you for your feedback.
