### ISSUE TITLE
[1.6.0b3] LFO Mess

### ISSUE THREAD

**Issue by trutypesounds** [polyend/TrackerBetaTesting#1487]
Well, altering the filter cutoff lfo amount in current instrument altering the same parameter in another instrument results in a mess. I guess its the same for other parameters, but didnt tried this yet... see video

https://user-images.githubusercontent.com/17484006/166251630-a84ab471-e171-49dc-8599-4fb65902a47c.MOV

https://user-images.githubusercontent.com/17484006/166251701-7f87182a-55a0-4e67-9b93-ee37bb3adced.MOV

**Comment by PRAYTHEPO** [comment]
I looks like every time you change any LFO parameter, all LFOs recalculate again. Looks like this, at least

**Comment by Jacknametrouble** [comment]
Fixed in 1.6.0b5 thank you for your help!
