### ISSUE TITLE
Timestretch algo enchancement 

### ISSUE THREAD

**Issue by trutypesounds** [polyend/TrackerBetaTesting#1489]
Is it in the plans to enhance the timestretch algo? I dont mind its slow calc times, but its very hard to get proper results, often causing unwanted artifacts.
Rubber band lib is a well known thing, everybody using it, Renoise used this via lua scripting first, later added as a native feature.

**Comment by Jacknametrouble** [comment]
There's no such plans. Thank you for your feedback.
