### ISSUE TITLE
Inconsistent shading on value sliders (1.6.0b)

### ISSUE THREAD

**Issue by dustboxednorth** [polyend/TrackerBetaTesting#1494]
With the implementation of this new theme, there seems to be some inconsistency between UI elements. In this case, its the value sliders in the Instrument Parameters menu. Snapshots didn't capture what's going on so I decided to take a photo of it instead.
![image](https://user-images.githubusercontent.com/56094177/166745573-5c1ae7d9-4f0a-4f31-b391-fdd91b3e955a.jpeg)

EDIT: sorry, probably should've set this to the "enhancement" label, since this could probably be seen as a really nit-picky thing :p

**Comment by Jacknametrouble** [comment]
Fixed in 1.6.0b5 thank you for your help!
