### ISSUE TITLE
Clarify license of PT instruments

### ISSUE THREAD

**Issue by jrfondren** [polyend/TrackerBetaTesting#1496]
The SD card that came with my Polyend Tracker contained this license.txt:

> All samples and projects included are licensed under a Creative Commons Attribution-NonCommercial 4.0 International license: https://creativecommons.org/licenses/by-nc/4.0/

Which I read to mean that the projects, the samples the projects include, *and the sounds under Samples/* can't be used in any commercial way. I.e., if I use the tracker to make a song with the 808 Kick from Concrete College's Drum Kit and sell the song, I've violated the license.

1. Do I read that license correctly? I'd hope at least that only the provided project's own samples were under this license and that the Samples/ directory was royalty-free...
2. Does this restriction also apply to the new .pti sounds under Instruments/ that come with 1.5.0?

I'd appreciate it if the manual remarked on this as well. I didn't notice the license.txt for a while.

**Comment by Jacknametrouble** [comment]
The licence applies to the samples used in the demo projects only.
