### ISSUE TITLE
"Open project" is too cumbersome to use with 30+ projects

### ISSUE THREAD

**Issue by jrfondren** [polyend/TrackerBetaTesting#1497]
Currently (on 1.5.0 and on 1.6.0b4) if I open a project all I see are the valid project directories under Projects/ on the SD card, and there isn't a browsable tree of projects like in the sample importer. With a long list of projects it's also a bit slow to scroll through them.

Could at least one level of subdirectories be added to this display?

I didn't mind this at all initially, but after loading 20 projects from Legowelt and your "What's New" posts, it became annoying to have to step through the list to find my own projects when I only occasionally want to look at the example projects. My solution was to put example projects in directories to hide them from the 'open project' listing, but that means that when I want to see them again I'll have to take out the sdcard, plug it into a computer, and move the directories back over.

Or, if the PT had a very simple midnight commander-style file manager onboard that could only move files/directories around on the SD card, that would let me manage the projects directory much more easily.

**Comment by Jacknametrouble** [comment]
This won't be possible due to the initial assumption on file management. Just use your computer to tidy up.
