### ISSUE TITLE
Mono Bass master feature

### ISSUE THREAD

**Issue by PRAYTHEPO** [polyend/TrackerBetaTesting#1498]
For example i use two tracks for bass, pan them max left and right to make it wide, but to avoid phase issues i want to sum all the frequencies below 120Hz into mono signal. Would be great to implement this feature as like in Ableton's Utility plugin (just example).

![image](https://user-images.githubusercontent.com/58429366/167033769-e1055330-07a3-4cad-83e0-51419ac81df9.png)

**Comment by Jacknametrouble** [comment]
Thank you for your feedback.

**Comment by PRAYTHEPO** [comment]
> Thank you for your feedback.

Does it mean that this will be implemented in next firmware?
