### ISSUE TITLE
[1.6.0b4 ] Midi cc on sample instrument triggers external (midi) instrument

### ISSUE THREAD

**Issue by arphex** [polyend/TrackerBetaTesting#1505]
### Steps to reproduce

Set the instrument of the step to an audio sample loaded in the project. When a midi cc  fx is chosen, this triggers an external instrument - even if the instrument selected in the step is *not* a midi instrument.

This happens every time as  far as I have seen.

This also leads to problems such as, when filling with random fx in an audio track, the patch on an external instrument is modified by ccs in case they show up due to randomness.  

it would be great to also have random fx *excluding* midi cc's, or disable midi cc if the instrument in the step is an audio sample and not a midi instrument.

(verified this with dreadbox typhon)

**Comment by oddiction** [comment]
Miro, I cannot reproduce this, **f-RandomFX** does not send out any MIDI CC, I've checked from 0-255.  Checked with MIDI over USB/Jack in a MIDI Monitor.

Can only make this happen when I add one of the _a-f MIDI CC_ fx to a step (which would be expected behavior for me).
