### ISSUE TITLE
Reverb Send and Delay Send per track/per instrument option

### ISSUE THREAD

**Issue by PRAYTHEPO** [polyend/TrackerBetaTesting#1511]
That would be nice option to be able to choose whether reverb and delay are attached to track or instrument

For example: 
1. Config menu
2. Project
3. Send FX (Per instrument/ Per track)

It can save some computing power and can be useful in situation when you use many different instruments which all are using reverb and delay; and they are placed on one track.

Example: 
Instrument 1 - Cmin chord sample
Instrument 2 - Cmaj chord sample

Both of them are using reverb and delay, and both of them are on track 2, so i find it very useful to assign this sends to the track for this project.

Also when this option (*per track*) is enabled, **reverb send** and **delay send** FX's in both columns of track decide how much of this **track** is going to the sends, *not* particular instrument. 

To configure send level we can use:
1. New page in reverb and delay settings where you see all the track names on bottom side of screen and adjust sliders
2. Or go to Master menu where you see all the track's levels, press Shift + Track button below screen, go to new menu where you can configure send level

Maybe this enhancement requires some new logic and significant rewrite of firmware code, but i find this very useful in most of cases.

**Comment by Jacknametrouble** [comment]
This also won't happen due to the limited hardware resources. Thank you for your feedback.
