### ISSUE TITLE
[1.6.0 b4] Export Samples just freezes machine

### ISSUE THREAD

**Issue by bambrose** [polyend/TrackerBetaTesting#1512]
steps to reproduce 👍 
Open project
Go to File : export samples
all controls unresponsive. Screen remains as is (indefinitely)
cancel has no effect
Unit freezes requiring hard reboot

**Comment by Synthdawg** [comment]
Reported already as #1478

**Comment by bambrose** [comment]
Sorry

**Comment by Synthdawg** [comment]
Haha no prob, better to report twice than not at all I would say.

**Comment by Jacknametrouble** [comment]
Duplicate of #1487

**Comment by Jacknametrouble** [comment]
Fixed in 1.6.0b5
