### ISSUE TITLE
[1.6.0b4] Typo in effect description

### ISSUE THREAD

**Issue by metawops** [polyend/TrackerBetaTesting#1513]
### Steps to reproduce

- Hold down FX1 or FX2 button and select the "f - Random FX value" effect.
- Open the description panel
- In line 6 there's "... value i 100, ..."
- This should read "... value is 100, ..."
- This was in firmware 1.5.0, too.
- See screenshot 

![image](https://user-images.githubusercontent.com/376090/168475894-0c03e0fa-5c8e-4775-9e25-e7b097778c31.jpeg)

**Comment by Jacknametrouble** [comment]
Fixed in 1.6.0b5 thank you for your help!
