### ISSUE TITLE
Alternative edit mode for single track

### ISSUE THREAD

**Issue by PITmast** [polyend/TrackerBetaTesting#1517]
Hi guys

Just a little idea how to insert notes in the same track without moving cursor and step jump function help.
Function available holding Rec button (when cursor switched to red) only.
First 48 steps on the track will highlight in pad grid with note entering/erasing ability on corresponding position.
Adding note by pressing pad adds root note only.
Adding/erasing note moves cursor to corresponded position.

This is the the scratch of idea only. Let's discuss if you want.
Let's make it clear - I don't want to make PT another PP of course :)

regards
Piotr

**Comment by Jacknametrouble** [comment]
Thank you for your feedback.
