### ISSUE TITLE
[1.6.0b5] Fill function is making the screen flash

### ISSUE THREAD

**Issue by natct10** [polyend/TrackerBetaTesting#1522]
## Hi, sorry to bother but 

The fill function is making my screen blink.

### Steps to reproduce

In pattern view, select steps and hit "fill" on instrument and the screen nlinks until I hit "cancel".

Please let me know if you need more detail!

With kind regards

**Comment by Jacknametrouble** [comment]
Any chance to take a look at a video showing the issue please?

**Comment by natct10** [comment]
Yes sure: https://natct.yourownnet.fr/s/KpaYcrbwys5Agxq

**Comment by Jacknametrouble** [comment]
Alright, nice one! Thank you for your help!. I guess 1.6.0b6 is coming soon :D Stay tuned!

**Comment by natct10** [comment]
Sure, please let me know if you need further details!

**Comment by Jacknametrouble** [comment]
This is fixed in [1.6.0b6]

**Comment by natct10** [comment]
Thank you, will test the new release soon! Cheers

**Comment by Jacknametrouble** [comment]
@natct10 thank you for your help!

**Comment by natct10** [comment]
By the way, the new theme looks really nice!

**Comment by natct10** [comment]
The issue is fixed, thank you!
