### ISSUE TITLE
[1.6.0b5] Fill Instruments 'To' name scrolling issue

### ISSUE THREAD

**Issue by PITmast** [polyend/TrackerBetaTesting#1524]
Scrolled name of 'To' instrument name is cut of to 2 signs.

https://mega.nz/file/jqZ3FIxZ#d1cO5oAuBiU_O1EMuPnIhsUfGCgCC9G-VLleDRZMwrI

regards

**Comment by Jacknametrouble** [comment]
This is fixed in [1.6.0b6]
