### ISSUE TITLE
FX fill via FX buttons

### ISSUE THREAD

**Issue by PRAYTHEPO** [polyend/TrackerBetaTesting#1527]
Very useful feature to minimize moves and button presses, as I think

1. Select few notes (steps)
2. Hold FX button, choose FX
3. Release FX button
4. All notes are filled with chosen FX

Example:

BEFORE
![image](https://user-images.githubusercontent.com/58429366/169583626-5a5c8156-5cab-4ace-8580-93ab08620370.jpeg)

AFTER
![image](https://user-images.githubusercontent.com/58429366/169583677-691a1e70-0881-4c08-b00f-403f28417eb7.jpeg)

**Fill** function is very useful, but the first thing that I think about when I want to fill steps with FX is what i described above

**Comment by Jacknametrouble** [comment]
Thank you for your feedback. The Fill tool is now complete and we really like how it wome out and how it works already.
