### ISSUE TITLE
Tables in instrument parameters

### ISSUE THREAD

**Issue by C0INPUSHER** [polyend/TrackerBetaTesting#1529]
Table-like features on an instruments parameters to make c64 styled arps/chords that way? Like LSDJ does. 
While the arp & chord fx are nice don't get me wrong I still don't get the arp feeling a tracker mostly has.
Also having tables to make arps and such on the instrument parameter itself would also kinda fix for instance the pan fx stopping the arp  AND  you'd still have 2 fx lanes free to do as you please.

**Comment by Jacknametrouble** [comment]
Thank you for sharing your idea. It would be a fun addition to have, but maybe in the future Tracker hardware version. The current one is already maxed out.
