### ISSUE TITLE
1.1.18 Scroll behaviour in the Song Screen

### ISSUE THREAD

**Issue by stevesomeone** [polyend/TrackerBetaTesting#153]
In song mode, when the playback head reaches the bottom of the arrangement (eg slot 13), the display does not scroll to display the rest of the arrangement. 

* How often does this bug happen? Constantly

* Does this bug happen in previous firmware versions? Yes, all firmwares

* Does this bug happen in every project? Yes all projects

**Comment by Jacknametrouble** [comment]
This was implemented some time ago.
