### ISSUE TITLE
[1.6.0b5] Sample Editor breaks Sidechain

### ISSUE THREAD

**Issue by PRAYTHEPO** [polyend/TrackerBetaTesting#1531]
After any action in sample editor (in my case it was Compressor) **sidechain track** parameter drops to *Disable* state without any visual cues.

It acts as like the track for sidechain is not selected and you need to switch **Sidechain Track** back and forth to make it work again as it was.

It happens not everytime. Cuz of that i cant claim that sample editor is the reason for this bug to happen.

**Comment by PRAYTHEPO** [comment]
Just got it again. I cropped the sample and bug appeared

**Comment by Jacknametrouble** [comment]
This is fixed in [1.6.0b6]
