### ISSUE TITLE
Double the pattern length from 128 to 256 for working better with higher rows per beat

### ISSUE THREAD

**Issue by Linkandzelda** [polyend/TrackerBetaTesting#1533]
The current pattern length of 128 is rather limiting when working with beat separation at 16 and higher tempo. With the current limits each beat takes up 16 rows with 1 bar taking 64 rows. That means only 2 bars can be fit into a single pattern.

It's more of an enhancement than a required feature since 4 or 8 bars in this method have to be split over 4 patterns instead of 2 if the limit was 256.

**Comment by Jacknametrouble** [comment]
This won't be possible due to the initial hardware/software assumptions. Thank you for your feedback. Best,
