### ISSUE TITLE
[1.6.0b6] Shift + Delete do not clear Master Volume to 0dB

### ISSUE THREAD

**Issue by PRAYTHEPO** [polyend/TrackerBetaTesting#1542]
Every parameter can be cleared to default state with Shift + Delete combination, but not Master Volume for some reason

**Comment by ziej8asek** [comment]
For master volume, pressing the Delete button increases the value in small steps up to 0 dB. This is a safety feature to prevent hearing damage in the event of a sudden increase in volume.
