### ISSUE TITLE
[1.6.0b6] Radio seek buttons issue in Sample Recorder

### ISSUE THREAD

**Issue by trutypesounds** [polyend/TrackerBetaTesting#1543]
When using dedicated decrease/increase buttons if you go up to 97.xx mhz freq it doesnt get upper, but it skips back to initial 87.5 mhz
Jog and up/down keys works ok

https://user-images.githubusercontent.com/17484006/171202408-b032c481-a256-4a05-a560-3b2a66ea076e.MOV

**Comment by MortalJS** [comment]
I checked out this topic. I am not able to approve it. In my case I am able to search for stations up to 107.7 then the search finds another station on the lowest frequency. This may depend on the radio signals the traker is catching. If the last one is on 97.xx then naturally it poisons the first station in the frequency range.

**Comment by trutypesounds** [comment]
> I checked out this topic. I am not able to approve it. In my case I am able to search for stations up to 107.7 then the search finds another station on the lowest frequency. This may depend on the radio signals the traker is catching. If the last one is on 97.xx then naturally it poisons the first station in the frequency range.

yeah, seems like it was random glitch, could not replicate this in b7
