### ISSUE TITLE
[1.6.beta5] Chance does not work on OFF steps

### ISSUE THREAD

**Issue by Raadiolained** [polyend/TrackerBetaTesting#1554]
### Steps to reproduce

Create a midi note. Or ordinary note, but I discovered it via midi.

Few steps ahead on the same track add OFF message.
Add Chance with a small almost nonexistent value, like "2" to that OFF message.

OFF message is not affected by Chance FX.
There is nothing to indicate that OFF should not be affected by Chance FX, since OFF message is still a note information. Thus I regard this as a bug or oversight.

I want chance to alter between long and short notes. 

### Attachments and links

Its easy to reproduce, no video.

### Other important information

* How often does this bug happen? every time

* Does this bug happen in previous firmware versions? yes

* Does this bug happen in every project? yes

**Comment by Jacknametrouble** [comment]
It's not really supposed to.
