### ISSUE TITLE
[1.5.0] Monitor input volume too low or too high and distorted recording

### ISSUE THREAD

**Issue by notaprogrammer9** [polyend/TrackerBetaTesting#1560]
### Steps to reproduce

The input monitor volume resets when exiting the sample recording screen. The input is close to inaudable when the tracker is playing back internal audio. 

Adding gain on the external device (connected to the input) results in clipping. 

Recording at a low volume results in aliasing and high pitched whine in the recording after normalizing the recording. 

When the bass in the Tracker is too high for the Tracker, the master summed audio sounds distorted. There is not enough headroom. There is no realtime instrument EQ to solve this problem.

* How often does this bug happen? (every time, often, "it only happened once")

All the time

* Does this bug happen in previous firmware versions?

Yes

* Does this bug happen in every project?

Yes.

**Comment by trutypesounds** [comment]
mentioned a long time ago here #1172 and there

**Comment by theodorozzz** [comment]
Hello! I have the same issue, but in one of projects it works as it should!
I mean line input signal plays in pattern mode without issues in of projects. Have no idea what the difference between them

**Comment by theodorozzz** [comment]
Ha. I found the reason. I miss that it have also fader in master section for line input. My bad! Solved for me though)
