### ISSUE TITLE
Bug => Clicks when using RV

### ISSUE THREAD

**Issue by anemlife** [polyend/TrackerBetaTesting#1566]
When using increasing volume rolls there are often clicks at the start of the rolls while there should be silent. Could it be improved? 

Thanks

**Comment by notaprogrammer9** [comment]
This is related to this issue:
https://github.com/polyend/TrackerBetaTesting/issues/1559

The clicking problem has been brought up several times, but Polyend is ignoring / unable to fix this problem. 

The only thing you can do is insert a volume change (without note information) right before the step with the clicking sound.

**Comment by MortalJS** [comment]
Duplicate #1559
