### ISSUE TITLE
[1.6] Inverted display on power up

### ISSUE THREAD

**Issue by LSnapes** [polyend/TrackerBetaTesting#1573]
![20220702_081914](https://user-images.githubusercontent.com/7988132/177008913-66e76e84-8395-41ec-a8bf-787cdcc6a846.jpg)

### Steps to reproduce

- Power on with shipped power supply.
- Screen momentarily looks like normal start up ,then screen suddenly inverts display showing reverse letters / inverted tracker.
- At first instance the the display would flick back and forth between normal and inverted at a very quick rate.
- If I power up using a power bank and a different usb type c , the graphics remain inverted but it no longer flicks back and forth
 to normal.

Also tried holding down power button while gently plugging in usb type C and on some instances that seemed
to control the inverting behavior such when the screen looked normal I would unplug it.

Using this technique described above, on power up( with a different usb type c & powerbank ) screen looks normal,
But half hour in the inverted / screen came back !

The bug seems electrical or perhaps static induced or hardware related,
like perhaps something is not soldered on right causing the display to flicker between normal and inverted.

**Comment by Jacknametrouble** [comment]
Hi @LSnapes this isn’t a firmware bug but a hardware malfunction of a display component. Please use https://help.polyend.com/submit_ticket to contact customer support, or head straight to your retailer in order to open up an RMA procedure.
