### ISSUE TITLE
v1.6.0 Problem of interpretation control change cc14

### ISSUE THREAD

**Issue by PaulAntioche** [polyend/TrackerBetaTesting#1579]
Contrary to what the manual says, I am happy to see that the MIDI synthesizer mode works when the tracker sequencer is playing.
But I discovered a problem: Problem of interpretation of the control change cc14 (Reverb Send). The values sent are correct but the reaction of p.t. is chaotic. The other controls work properly.

**Comment by MortalJS** [comment]
Hi @PaulAntioche,

Can yourecord some video and attach to ticket?

**Comment by PaulAntioche** [comment]
sorry. it's working now. probably a cable problem.
Paul
