### ISSUE TITLE
4 Tracks Stéréo mode and Colored Paterns 

### ISSUE THREAD

**Issue by bfasseke** [polyend/TrackerBetaTesting#1587]
Maybe an idea for the next update? The Tracker can play 8 Mono tracks simultaneously , why not give the possibility of activating a 4-track Stereo mode (2 mono per track). Just an idea!!😉 

Also the possibility to have a different color for each patern in the patern view?  Thanxx!

**Comment by Jacknametrouble** [comment]
The hardware limitations (almost maxed out already) won't allow us to implement any of the suggested features. But in the future hardware versions, why not? :) Thank you for your feedback.
