### ISSUE TITLE
[1.6.0] difference between audio output and audio exported

### ISSUE THREAD

**Issue by tomasoma** [polyend/TrackerBetaTesting#1594]
## I notice a significant difference between the rendering of the audio output and the result of a song export

I link a dropbox folder with 2 files of the same song, in the same state of the project, all exactly similar. one is the song export "master-5.wav" and the other is the output recorded and normalised (-0.3 db) "PT24B1.wav" 

https://www.dropbox.com/sh/s8h3s13rfdxm9zd/AAAfg21hAvPNyiYa-11tM6z_a?dl=0

Is this known ?
Is this normal ?

**Comment by PRAYTHEPO** [comment]
@tomasoma what to look at? What you want us to notice? Difference between volume level?

**Comment by tomasoma** [comment]
@PRAYTHEPO No, Please ...
I added 2 files in the same folder : 4 bars cuted from each files at around 0'54" 
take some correct headphones, i have cheap JBL and i can't miss the difference : 
Export : more volume, the fx are far away
Output : less volume, the fx are louder.

Even if the volume level is globally louder on the export, why is the reverb so far away ?
I guess the difference of global volume is pretty normal, but shouldn't we able to trust the output to mix the fx to export the song ?
clearly the fx are not treated the same way.

I hope my comment is clearer now.

**Comment by PRAYTHEPO** [comment]
@tomasoma i will check a bit later. I noticed some difference at reverb level, but was listening through JBL in-ear headphones. Will check through my AKG. Interesting...

**Comment by PRAYTHEPO** [comment]
@tomasoma
Hi again. Listened carefully through headphones. Yes, difference is obvious, but i think this is not a bug. I think that when you export song it does some audio processing which we don't know about

**Comment by tomasoma** [comment]
Hi @PRAYTHEPO
well really ? 
So I repeat my question : shouldn't we able to trust the output to mix the fx to export the song ?

> Yes, difference is obvious, but i think this is not a bug
I don't know the exact definition of a bug, but this is still a problem as a user, because i expect to be able to trust the output to make my mix and export my song.

> when you export song it does some audio processing which we don't know about
Aren't you a Polyend staff ?

**Comment by PRAYTHEPO** [comment]
@tomasoma no, i am just community member. Are you sure that you didn't tweak anything right before export? Cuz i just made a comparison of my own mix through output recording and export, and they sound pretty much the same, as i can hear. Which firmware version are you using?

**Comment by tomasoma** [comment]
@PRAYTHEPO ok
Yes i'm totally sure i didn't tweak anything between export and output record.
the version of the firmware is in the title : [1.6.0]
Polyend staff seems to have deserted this github trackerBetaTesting pages :/

**Comment by PRAYTHEPO** [comment]
> @PRAYTHEPO ok

So it's very strange. Yesterday i exported my new sketch and i don't see difference between usual output and exported .wav.
Which revision of PT u use? Maybe this is the case. (As i know, the hardware is the same, only the case got changes from metal to plastic. But who knows...)
My main conclusion that this is some audio processing on finalizing song
> Yes i'm totally sure i didn't tweak anything between export and output record.

Sry, didn't see 😅
> the version of the firmware is in the title : [1.6.0]

Yeah, dust covers this pages for a month after they released Polyend Play
> Polyend staff seems to have deserted this github trackerBetaTesting pages :/

**Comment by MiroPoly** [comment]
This is by design: export happens before Bass Boost, Space and EQ master FX.
