### ISSUE TITLE
[1.6] Volume envelope smooths transients

### ISSUE THREAD

**Issue by jarkkojs** [polyend/TrackerBetaTesting#1607]
### Steps to reproduce

1. Set kicks volume envelope with sustain set 100.
2. Listen high transient kick with volume envelope turned off.
3. Listen high transient kick with volume envelope turned on.

Transients are a bit smoothed. This is especially easy to hear with "psytrance" type of kick drums. This introduces a problem that you can either fail with mixing because kick has changed or fail with having clicks because of not having a short release time.

### Attachments and links

I can render kick with both options on request.

**Comment by PRAYTHEPO** [comment]
@jarkkojs did you set attack to 0.00 secs?
