### ISSUE TITLE
[1.21] switching from Master to Perform sometimes shifts tracks time-wise

### ISSUE THREAD

**Issue by sebpmtl** [polyend/TrackerBetaTesting#349]
Let's say you're in Perform mode and have pattern 1 playing along with pattern 3, if you go to Master to solo a track and come back to Perform, the track with pattern 3 will play shifted..To retrigger it from the start, I have this little trick that I use: I'll press really fast on the track select button (in Perform).. I tried that trick to layer, let's say, a 7/8 arpeggio over a 4/4 beat. It works and you can even retrigger the arpeggio from the start also by using the same trick... Not sure if it's supposed to work that way. It'd be great if it didn't retrigger the pattern from the start just by changing modes. (master to perform).... it doesn't always do it though..

**Comment by MortalJS** [comment]
Hi @sebpmtl 
Can you check if the problem occurs in firmware 1.5?

**Comment by MortalJS** [comment]
No response. Closed
