### ISSUE TITLE
[1.3.0b3] Unable to load sample

### ISSUE THREAD

**Issue by modmodmodmod** [polyend/TrackerBetaTesting#519]
When I create a new project and try to load the sample, the sample loader does not preview the sample.  It cannot be added.  Even the new import function cannot be previewed or loaded.  Then press the master button to freeze.  I have backed up all the projects and updated them, so it's okay, but I can't make any new songs with 1.0.3b3.  Please check the video linked.

https://drive.google.com/file/d/1bV1IO-GsCOn4giNIK3pafdC51Z7mzFaw/view?usp=drivesdk

* How often does this bug happen? 

every time

* Does this bug happen in previous firmware versions?

no

* Does this bug happen in every project?

The problem is even more serious in other projects.  I can't even open the project.  I have some projects open, but when I try to import the sample, it says that the non-empty folder is empty.  The errors vary from project to project, but I can't load the samples into multiple projects I've tried so far, and they freeze quickly.

**Comment by piotr3500** [comment]
Seems like a problem with sd card. 
Does it happen on 1.3?
