### ISSUE TITLE
[1.3.0] Pattern from Song Screen goes to previous, not current played

### ISSUE THREAD

**Issue by sunegg1024** [polyend/TrackerBetaTesting#698]
### Steps to reproduce

If you are on Song Screen and, say, it is playing Pattern B. If you then hit the Pattern button, it goes back to the previous pattern you were editing and not the Pattern that was just playing in the Song Mode. This is confusing because likely you are listening to the song mode and want to make a change in the Pattern you were just hearing so many many times I have simply pressed Pattern and started editing only to find out I'm editing the wrong pattern. I know this is a simple thing to fix (check the Pattern and navigate to the right one) but I can't imagine a scenario where you wouldn't want to jump straight to the patter you were just listening to. 

### Attachments and links
 
Can send a video if needed but pretty self-explanatory, I think!

### Other important information

* How often does this bug happen? (every time, often, "it only happened once"): **Every time**

* Does this bug happen in previous firmware versions? **Not tested**

* Does this bug happen in every project? **Yes**

**Comment by tfspsound** [comment]
I think I’d like it if I was in Song mode and I was playing the song that when I pressed Pattern it went to the current pattern that was playing and looped that pattern, then resumed the song when I press Song again. I like that the tracker retains pages as well though particularly with the sample editors and mixers etc.
