### ISSUE TITLE
[1.3.0] Undoing Song Screen Pattern deletion does not return data until a different pattern is played

### ISSUE THREAD

**Issue by sunegg1024** [polyend/TrackerBetaTesting#699]
### Steps to reproduce

If you are in song mode and you delete a pattern that has note data in it but then immediately undo that deletion and play the pattern, the note information will not return until you play a different pattern and then return back to the first. You can even go in to the pattern screen and notice that no data from the deleted/undeleted pattern is there. It will, however, return once you play a different patter.
1) create pattern in Track 1, Pattern A
2) create pattern in Track 1, Pattern B
3) Play the pattern
4) delete Track 1 in pattern B, then undo the deletion.
5) Play Pattern B and notice it has no note data. (optional: hop in to the pattern and notice there is nothing there)
6) Play Pattern A then back to Pattern B and notice that B is now successfully undeleted.
7) Confirm by going in to to Pattern B Pattern screen and seeing the note data

### Attachments and links

Can send a video if needed - let me know!

### Other important information

* How often does this bug happen? (every time, often, "it only happened once"). **Every time**

* Does this bug happen in previous firmware versions? **Not tested**

* Does this bug happen in every project? **Yes**

**Comment by MortalJS** [comment]
Hi @sunegg1024 

Can you check if the problem occurs in firmware 1.5?

**Comment by MortalJS** [comment]
Closed. No response
