### ISSUE TITLE
[1.3.0] rXX and tXX values disregarded if not next to Note Trigger

### ISSUE THREAD

**Issue by sunegg1024** [polyend/TrackerBetaTesting#702]
### Steps to reproduce

Place a note with sample and the place an rXX or tXX value a few steps down (choose a sample with a long decay). rXX and tXX appear to be disregarded (don't send to reverb and delay) if they don't land on the same step as sample trigger. Shouldn't it be that rXX and tXX send whatever is audible on that track whenever it is engaged? Not sure if this is a big or feature request, honestly.

### Attachments and links

Often the best way to show the problem is to record a short video,
attach the Tracker project you were working on, and provide links.

Can send video, as needed.

### Other important information

* How often does this bug happen? (every time, often, "it only happened once") **Every time**

* Does this bug happen in previous firmware versions? **Not tested**

* Does this bug happen in every project? **Yes**

**Comment by MortalJS** [comment]
Hi @sunegg1024 
Can you check if the problem occurs in firmware 1.5?

**Comment by MortalJS** [comment]
No response. Closed
