### ISSUE TITLE
[1.3.1.b2] Current Pattern display on Grid doesn't update when using cursor button + new idea

### ISSUE THREAD

**Issue by talktogreg** [polyend/TrackerBetaTesting#723]
When you hold down the Pattern screen button, you get to see a dimly lit list of occupied Patterns, as well as a fully illuminated button for the current Pattern.

If, whilst hold Pattern screen button, you click on of the dimly lit cells on grid, the Pattern changes (instantly) and the selected button goes fully illuminated to indicate this.

But, if instead, whilst holding Pattern screen button, you use UP or DOWN cursor keys to change Patterns (instantly), the Patten change occurs, but grid lights do not update until you release and re-press Pattern screen button.

As a very related new suggestion, could the queued next Pattern (when Pattern screen button + LEFT of RIGHT is used) <blink> dim/bright the pending next Pattern grid light, then update as per instant changes above ?

**Comment by MortalJS** [comment]
Hi @talktogreg 
Can you check if the problem occurs in firmware 1.5?

**Comment by MortalJS** [comment]
No response. Closed
