### ISSUE TITLE
[1.3.0] Asymmetric Import of Single Cycle Waveforms

### ISSUE THREAD

**Issue by mxactvtd** [polyend/TrackerBetaTesting#743]
## Serious Asymmetric distortion when importing Single Cycle Waveforms 
When importing single pure Sine and Saw waves of specific hz in 16bit 44.1k, there are noticeable problems in the interpretation on the data,  for example the positive half-cycle might be considerably longer or there is a sudden straight line, or complete phase shift of the sample, like it does not fit properly, a cool effect sometimes, but far from accurate and very random distortion based on the Hz and length of sample.

I think this likely is the result of the internal Length parameter being in miliseconds having too low precision to do the correct interpretation of the sample, maybe use a double instead of a float if possible, or at least less rounding. Preferably just do it based on the actual number of Samples if possible!

### Steps to reproduce
Make nice single-cycle waves of diffeerent frequencis with perfect shapes, load them in, and observe :)
This bug does not appear in 440 hz

### Thank you!!!
Thanks Polyend for making nearly perfect hardware, and this github to keep improving the quality of the software, amazing job!

**Comment by MortalJS** [comment]
Hi @PaulAntioche
Can you check if the problem occurs in firmware 1.5?

**Comment by MortalJS** [comment]
No response. Colsed
