### ISSUE TITLE
[1.3.1b3] Holding shift on master page (2/3 & 3/3) freezes the screen

### ISSUE THREAD

**Issue by Displeak** [polyend/TrackerBetaTesting#745]
Simply holding shift on one of these screens for about 1 sec freezes the screen.
Happens every time

**Comment by Just-Peter** [comment]
That's normal behaviour and is meant to Solo and Un-solo tracks.

**Comment by blasphemer420** [comment]
> That's normal behaviour and is meant to Solo and Un-solo tracks.

I believe the issue is Tracker is freezing/completely unresponsive once the action is performed.
