### ISSUE TITLE
[1.3] Saving Project/Song Problem with same Characters at Name

### ISSUE THREAD

**Issue by positionhigh** [polyend/TrackerBetaTesting#747]
"Saving as" seems to be a problem if the first characters of the Folder/Project Name are the same. The resulting project is not saved or listed in the browser.

### Steps to reproduce

save a project with a new name starting with the same 12 ? 14? characters at the beginning.

the project will be invisible in the browser if an other project with the same starting characters exists.

**Comment by MortalJS** [comment]
Hi @positionhigh 
Can you check if the problem occurs in firmware 1.5?

**Comment by MortalJS** [comment]
No response. Closed.
