### ISSUE TITLE
[1.3.1b2] Mass change of notes doesn't work

### ISSUE THREAD

**Issue by clickysteve** [polyend/TrackerBetaTesting#751]
### Steps to reproduce

Good:

1. Select multiple steps in a single column.
2. Hold down instrument button and select a new instrument.
3. All steps selected change to that instrument.

Bad: 

1. Select multiple steps in a single column.
2. Hold down note button and select a new note.
3. Only one step changes to the new note.

You can obviously still mass change notes by manually jogging through the wheel with them all selected, but this behaviour is unexpected and inconsistent with the rest of the UX.

### Other important information

Every time, every project. Not confirmed with previous firmware versions.

**Comment by MortalJS** [comment]
Hi @clickysteve 
Can you check if the problem occurs in firmware 1.5?

**Comment by MortalJS** [comment]
No response. Closed
