### ISSUE TITLE
[1.3.b2] recorded notes one entire step late consistently

### ISSUE THREAD

**Issue by bambrose** [polyend/TrackerBetaTesting#755]
### Steps to reproduce
With microtiming and velocity turned off in the options.
When live recording on an armed track (playing samples)
Recording sounds in time while recording. On playback however all notes are exactly one step late (so going to top row and selecting backspace returns entire track to correct timing)

### Attachments and links

Often the best way to show the problem is to record a short video,
attach the Tracker project you were working on, and provide links.

Pro-tip: You can drag and drop images and `.zip` files directly to the edit
box when writing your bug reports. Videos are too big as attachments, you
will have to use an external service for this and provide us links. Please
don't use services that delete files after short periods of time.

### Other important information

* How often does this bug happen? (every time, often, "it only happened once")

* Does this bug happen in previous firmware versions?

* Does this bug happen in every project?

**Comment by MortalJS** [comment]
Hi @PaulAntioche
Can you check if the problem occurs in firmware 1.5?

**Comment by MortalJS** [comment]
No response. Closed.
