### ISSUE TITLE
[1.3] Text from FX page overlaid on other instrument param pages

### ISSUE THREAD

**Issue by bn-mk** [polyend/TrackerBetaTesting#759]
Go to instrument parameter page
Click into the FX section
Press instrument parameter page button
text from FX page is is overlaid on the new param page

This happens consistently on each project. Not sure if it was present in previous firmware versions

**Comment by Folkhogskola** [comment]
I can definitely say I’ve experienced this issue on version 1.3.0. Not consistently. I’d say only occasionally if I’m zooming back and forth between pages. 
👍🏻

**Comment by Supernatural802** [comment]
for me, I can reproduce this glitch every time on any project in 1.3.0

**Comment by MetabaronCZ** [comment]
I think this problem should be repaired in latest beta:
https://github.com/polyend/TrackerIssues/issues/595
