### ISSUE TITLE
[1.3.1B3] Notes not triggering after first note entry as midi slave

### ISSUE THREAD

**Issue by rpc9943** [polyend/TrackerBetaTesting#770]
### Steps to reproduce

1. have another gear send midi clock/transport to tracker
2. play a midi note / sample , you will hear it trigger
3. try another note, will not retrigger until transport on external midi starts/stops

### Attachments and links

Often the best way to show the problem is to record a short video,
attach the Tracker project you were working on, and provide links.

Pro-tip: You can drag and drop images and `.zip` files directly to the edit
box when writing your bug reports. Videos are too big as attachments, you
will have to use an external service for this and provide us links. Please
don't use services that delete files after short periods of time.

### Other important information

* How often does this bug happen? (every time, often, "it only happened once")
every time

* Does this bug happen in previous firmware versions?
Unsure, probably

* Does this bug happen in every project?
yes

**Comment by MortalJS** [comment]
Hi @rpc9943 
Can you check if the problem occurs in firmware 1.5?

**Comment by MortalJS** [comment]
No response. Closed
