### ISSUE TITLE
[1.3.1b3] MAIN mixer MUTE issue

### ISSUE THREAD

**Issue by talktogreg** [polyend/TrackerBetaTesting#797]
If you have a looped beat/melody that fills a Track (ie length matches step count) then the following occurs:

If you MUTE the Track on Pattern Page - _Sequence Mute_
- track will play till end of loop, then not play again until it is re-triggered after un-Muting: CORRECT

If you MUTE the Track on Main Mixer page - _Audio Mute_
- audio will Mute/un-Mute immediately as expected: CORRECT

However, if on Main Mixer you
- Mute, then subsequently un-Mute after the Track has looped, it will not audibly play until it is re-triggered: WRONG

**Comment by MortalJS** [comment]
Hi @talktogreg 
Can you check if the problem occurs in firmware 1.5?

**Comment by MortalJS** [comment]
No response. Closed
