### ISSUE TITLE
Hold down Slice  pad to adjust start position 

### ISSUE THREAD

**Issue by cclcng** [polyend/TrackerBetaTesting#823]
### A feature request :

In the interest of greater fluidity when editing samples / slices , i thought of a neat idea foR editing start points.... so, holding down a slice’s  corresponding pad, would enable the user 🥈 adjust the start point uv that slice until the pad is  released. Thanks !!

**Comment by Nodoubtyall** [comment]
Yes, we need this 😊

**Comment by soffer** [comment]
Great idea

**Comment by darenager** [comment]
+1 yes it would speed up slicing.

**Comment by bambrose** [comment]
Been asked for before. But yes this would enhance workflow considerably

**Comment by danapeks** [comment]
Just linking through previous requests for this as there are multiple over the last year #217 #335 #485 #782 #815 #823
Really be good to get an update from someone at Polyend as to whether this is being looked at and is possible?

**Comment by Jacknametrouble** [comment]
Would be a cool addition @ambv

**Comment by trutypesounds** [comment]
+1 yes pls

**Comment by danapeks** [comment]
Even just using the pads (rather than holding down) to select the slice you are editing would be a great improvement

**Comment by Jacknametrouble** [comment]
Implemented in v1.5.0
