### ISSUE TITLE
[1.3.0 and 1.3.1b3] Clipping with LP filter Resonace 100

### ISSUE THREAD

**Issue by karachinsky** [polyend/TrackerBetaTesting#828]
So, turning the filter up and down with extreme 100% resonance, I've found that it behaves like an overdrive, adding high frequency noises.

Track with the sample was set to low volume, master is also in a green zone.

I have same issue with a single cycle waveforms and one-shots. 
Maybe I get something wrong, but closed LP filter means you won’t hear any high frequencies.

https://youtu.be/lzNosuSSipE

**Comment by MetabaronCZ** [comment]
I have also some problems with resonance with single cycle waveforms. Thank you for reporting this. I found that even low resonance about 15 is making some weird noises sometimes - mainly when using Filter LFO. Safe value is about 5.

Filter resonance functionality should be revised.

**Comment by modulationsource** [comment]
It seams there is no headroom in the internal audio path.
So if the sample is normalized to 100 % and the resonance adds volume, it clips internally.
At the moment you can solve this by normalizing the sample to 50-75 %, than in most cases the clipping is gone.

**Comment by karachinsky** [comment]
> At the moment you can solve this by normalizing the sample to 50-75 %, than in most cases the clipping is gone.

Clipping gone at 25% for the low notes, but now I get same noise playing that sample in higher octaves.

**Comment by MetabaronCZ** [comment]
@modulationsource Oh, thanks for tip. I will try it.

**Comment by rjvaleo** [comment]
I haven't done extensive research on the exact nature of the clipping, but I have found that there is serious clipping with resonance turned up past 50% on a sound with moderate volume.

**Comment by MortalJS** [comment]
Hi @karachinsky 
Can you check if the problem occurs in firmware 1.5?

**Comment by MetabaronCZ** [comment]
Hello. I just tried it and the problem is still there in 1.5.0.

As has been said, the problem is with small headroom of tracker. If I load a piano sample and play a sequence and play with filter cutoff, just setting resonance to 5 - 10 starts clipping sound and higher values start distortion. And same problem is of course with filter LFO.

**Comment by MortalJS** [comment]
Still in 1.5
