### ISSUE TITLE
[1.3.1] LFO's (for example volume, cutoff) reacting different when externally clocked

### ISSUE THREAD

**Issue by doelman** [polyend/TrackerBetaTesting#889]
Hi, 

I'm working on a project where I use the LFO functionalities a lot. I created the project using the internal clock. Now I want to combine it with Ableton and externally clocked the tracker. All instruments with LFO elements react totally different and basically the whole thing sounds messed up. 

Externally clocking projects which don't use the LFO's works perfectly fine. I checked on 1.3.1 beta 3 and the problem was already there as well.

So the main problem is that the instruments that use LFO's (on volume, cutoff, panning), both in instrument definition and in the pattern FX lane for changes are messed up. 

Roeland
[smelly party 4.zip](https://github.com/polyend/TrackerIssues/files/6136236/smelly.party.4.zip)

**Comment by doelman** [comment]
btw, resetted the config as suggested in another topic.

**Comment by sunguild** [comment]
I was just coming here to post this one. I had an LFO going to cutoff, it seems to reset the phase of the LFO at about the rate of a 16th note when an external clock is received. However, when I tried adding an LFO to volume or panning to trouble shoot, those were unaffected. Have you tried this?

**Comment by doelman** [comment]
@sunguild volume also effected but maybe it depends on the sample and/or LFO rate. Very frustrating, everything I think I have found the right setup to jam some new troubles pop up.

**Comment by ROM72** [comment]
Same thing here, the LFO is not doing what it's supposed to do when the tracker is slaved, is super annoying.

**Comment by MortalJS** [comment]
Hi @doelman 
Can you check if the problem occurs in firmware 1.5?

**Comment by MortalJS** [comment]
No response. Closed
