### ISSUE TITLE
[1.3.1] Rendering freezes device

### ISSUE THREAD

**Issue by chris-roerig** [polyend/TrackerBetaTesting#891]
### Steps to reproduce

Select all tracks and then render to sample.

### Other important information

* How often does this bug happen? every time

* Does this bug happen in previous firmware versions? no

* Does this bug happen in every project? yes

## Notes

The screen would load the rendering image bug the progress bar would stop around 1%.
Turning off the device is the only way to quit. 
Rendering with the same name gets an error "file with that name already exists" but the file is not visible in the folder browser

**Comment by dirtysampling** [comment]
Same with, rendering any track freezes my unit. Can't even turn it off. I need to unplug the cord.

**Comment by coreywonggithub** [comment]
Same here. Rendering anything freezes the tracker completely. On 1.4.0

**Comment by MortalJS** [comment]
No response. Closed.
