### ISSUE TITLE
[1.30] Crickets in my Tracker (bug)

### ISSUE THREAD

**Issue by notaprogrammer9** [polyend/TrackerBetaTesting#901]
There seems to be a strange software issue with my unit. 

I’ll try to explain...

When I create a new project or load an existing project (created and saved with 1.30), when I add more gain to the master level, I hear the sound of crickets and a little bit of noise (similar to white noise). 

Here’s the strange part: 
When I load a project (into firmware 1.30) created and saved with a previous firmware (the one that was installed when I purchased the unit), there is no noise or crickets. The output is completely noise free. 

When I go into sample recorder and disable the monitor input, the crickets disappear until I exit the sample recorder window.

Both projects share the same project settings.

While it looks like it is most certainly a siftware issue, I have tried the following:
- different wall socket
- Remove all cables (except for headphones)
- Dimmed the screen brightness (which introduces a low freq buzzing sound. Very different from crickets)

I would like to know if there’s anything I can do about this. I don’t like the sound of crickets that much. 

Thank you very much

**Comment by gurkenkimchi** [comment]
I'm having the same problem.

**Comment by Jacknametrouble** [comment]
Does it change anything when Master Mixer 3/3 Live input monitoring is turned off? Does it change anything when there's a jack cable inserted in the input port?

**Comment by notaprogrammer9** [comment]
Hello
Both questions I have already answered in my initial post! ;-)

1/ yes, but only when in Sample Recorder
2/ no

**Comment by notaprogrammer9** [comment]
Sorry, I mistead your question, Jack.

when line in is muted in the mixer, the noise and crickets are gone

**Comment by Jacknametrouble** [comment]
"when the line-in is muted in the mixer, the noise and crickets are gone." As far as I know, this is a known thing and considered a firmware bug. Should be soon resolved in one of the coming updates. For now, just please mute the Live input monitoring.

**Comment by notaprogrammer9** [comment]
Yes, so the input is noisy. 
The noise is printed into the recording. 
With all due respect, but how do you know this is software related? The noise is similar to USB interference. Which makes sense as it gets power over a USB cable. 
How does something like this gets solved by changing code? 
You also mentions it will get solved in a future firmware. Is there an ongoing ticket currently on Github about this issue?

**Comment by Jacknametrouble** [comment]
The input is handled by the codec, the codec is programable by the firmware.

**Comment by notaprogrammer9** [comment]
Hm ok...
There are two problems here:
- The noise is printed into the recording (sample)
- If I mute the input, I need to run the output of the Tracker into for example the A4. But because the Tracker has very high audio latency, my sequences are not in sync. I use the Tracker for drums, and so they are late. 
Which means I have to sync everything manually until the latency issue is solved. I’ve read this will be solved in 1.4?

I have all of my fingers crossed for a nice firmware update that solves both of these problems 🤞🏻

**Comment by notaprogrammer9** [comment]
Anyway, please remove these crickets from my recorded samples in the next update. 
thanks.

**Comment by notaprogrammer9** [comment]
I see no mention in 1.3.2 or 1.4 about this issue?
In the list of “milestones”.
This is important stuff 🥺
I can not record any sounds until “the codec” is fixed
