### ISSUE TITLE
[1.3.1] Exported files often have loud noise.

### ISSUE THREAD

**Issue by modmodmodmod** [polyend/TrackerBetaTesting#902]
The link below monitors the pattern with protools. This is the noise in two places that are being clipped. This example is v1.3.1, but I have often seen this error in previous versions and other projects.

https://drive.google.com/file/d/1CoY0Q777XUvGNbV2Ldjr6VbTef_HqjjX/view?usp=sharing

**Comment by bambrose** [comment]
I've experienced this as well
A blast of white noise when exporting by visible on the waveform. For me it happens at the end of the first bar

**Comment by clickysteve** [comment]
<img width="933" alt="Screen Shot 2021-09-27 at 00 22 27" src="https://user-images.githubusercontent.com/6227598/134827786-b72dc3bc-ec63-4c7b-8c6c-66d9caf34945.png">

Still an issue in 1.4.0.

**Comment by MortalJS** [comment]
Hi @modmodmodmod @clickysteve 
Can you check if the problem occurs in firmware 1.5?

**Comment by MortalJS** [comment]
No response. Closed
