### ISSUE TITLE
[v.1.3.1] Preview while playing Pattern 

### ISSUE THREAD

**Issue by thebradclay** [polyend/TrackerBetaTesting#906]
### Steps to reproduce

Create pattern. Play Pattern. Press Preview on step with a sample while pattern is playing. Pattern continues to play where as before the pattern would stop and you would here the preview'd sample. EDIT: While a pattern is playing pressing preview does not play the selection at all.

### Other important information

* How often does this bug happen? Every time

* Does this bug happen in previous firmware versions? No

* Does this bug happen in every project? Yes

**Comment by fairchild670** [comment]
Just wanted to add that it would be great so that "Preview" would play whatever sample is at that step without the pattern stopping while in Edit mode. Auditioning sounds while the pattern is playing would be incredibly helpful.
