### ISSUE TITLE
[1.3.1] length of a pattern not respected

### ISSUE THREAD

**Issue by loktez** [polyend/TrackerBetaTesting#908]
If I copy a pattern to another pattern and change its length on that new pattern, the reading head exceeds the length entered. I have to save, turn off the Tracker and then the length is respected. Also sometimes the pattern displayed does not match the right pattern played.

### Other important information

* How often does this bug happen? Often

* Does this bug happen in previous firmware versions?
Don't think so.

* Does this bug happen in every project?
Yes.

**Comment by loktez** [comment]
the video :

https://user-images.githubusercontent.com/76638021/113166990-924e4800-9243-11eb-868b-11a83254ad8e.mov

**Comment by loktez** [comment]
It seems that pass to the perform mode and comeback to the pattern mode unlock the good lenght.

**Comment by MortalJS** [comment]
Hi @loktez 
Can you check if the problem occurs in firmware 1.5?

**Comment by MortalJS** [comment]
No response. Closed
