### ISSUE TITLE
v1.31 slice mode bug

### ISSUE THREAD

**Issue by BlakRainbow** [polyend/TrackerBetaTesting#924]
in pattern edit screen: when entering notes/slices into track 1 pattern slices light up on the pads and work fine, but when i move to track 2 and enter notes, and then return to track 1 the pads change to chromatic mode (and are unlit). I have to reload the instrument on track 1 and then everything works normally and the pads light up again indicating all of the slices.

**Comment by MortalJS** [comment]
No response. Closed
