### ISSUE TITLE
[v1.3.1] Volume Fx Clicking

### ISSUE THREAD

**Issue by Unsettled-Sound** [polyend/TrackerBetaTesting#944]
Hi,

I have been trying to use the volume effect on FX 1. Everytime I do this I get a clicking sound from the track. If I remove the effect the clicking stops. The clicks are not consistent. Sometimes it is one of two per loop cycle, sometimes more. The clicks are always there though. 

I am new to the Tracker so this is the first firmware version I have tried (v1.3.1).

**Comment by trutypesounds** [comment]
It's still in 1.4.0, on low values volume fx makes sample sound kind of super snappier/clickier (the lower the value the more it snaps/clicks) like its not a volume down function but a hard compressor function @ambv

**Comment by KezzieCoyote** [comment]
This issue appears on firmware version 1.4.0 when automating volume parameters during sample playback, it will create a clicking sound as it instantaneously jumps to the next value. A simple fix could be a millisecond or two envelope while it transitions to avoid this popping noise.

Here's a video showcasing and then describing the issue:
https://youtu.be/Y_PFj4bN8XM

**Comment by MortalJS** [comment]
Hi @Unsettled-Sound 
Can you check if the problem occurs in firmware 1.5?

**Comment by MortalJS** [comment]
No response. Closed

**Comment by MaxDesiatov** [comment]
This still occurs for me with firmware 1.5.0

**Comment by faulex** [comment]
> This still occurs for me with firmware 1.5.0, for both Volume and Low-Pass Cutoff FX.

I'm also having this Issue on 1.5.0

**Comment by madwreck** [comment]
I am experiencing this issue with volume and lp cutoff fx as well - firmware 1.5

**Comment by trutypesounds** [comment]
its still in 1.6 betas @MortalJS
