### ISSUE TITLE
[1.3.1] Sample loader bug alert

### ISSUE THREAD

**Issue by modmodmodmod** [polyend/TrackerBetaTesting#959]
When loading an instrument on the Sample loader screen, an alert to replace an empty instrument number is frequently displayed.

This bug also existed in past versions.
This bug also existed in other projects.

![IMG_4344](https://user-images.githubusercontent.com/45414776/113498024-2c640800-9544-11eb-8c5f-7d320d9474bf.jpg)

**Comment by bambrose** [comment]
Yes I've seen this too.
I think it occurs when an sample has been previously assigned to that spot and then deleted. So the spot is empty but is not recognised as such by the tracker
