### ISSUE TITLE
[1.3.1] master track volumes impact sample loading and playback preview

### ISSUE THREAD

**Issue by gordwithers** [polyend/TrackerBetaTesting#988]
1. Create a track with various samples, etc
2. on the master volume screen (2/3), go to track one, and lower the volume to very low
3. go to the sample  playback screen and preview any sample - you can't hear it
4. or, go to the sample loader screen, and try to preview any of the instruments that you have loaded into the "instruments" column - you cannot hear them.
very confusing!

* Does this bug happen in previous firmware versions?
I've only been on the latest version, so cannot say

* Does this bug happen in every project?
Yes - well, it happens in my projects, and I just tested against the Tim Koch Unnatural Knit and it does it there too.

**Comment by MortalJS** [comment]
Hi @gordwithers 
Can you check if the problem occurs in firmware 1.5?

**Comment by MortalJS** [comment]
No response. Closed
