### ISSUE TITLE
[1.3.1] Volume adjustments on master volume 2/3 are clicky

### ISSUE THREAD

**Issue by gordwithers** [polyend/TrackerBetaTesting#989]
### Steps to reproduce
1. Load a song and play (song mode or just play a pattern)
2. open the master volume screen (2/3) with all the tracks
3. change the volume using the scroller wheel
4. here clickiness when adjusting volume up or down 
5. easiest to hear on longer notes, playing over more then one step

you can hear this on Starkey - First Explorer song.
- go to pattern 3 and play it only
- mute all tracks except track 3
- while track three is playing, turn the scroll wheel to adjust volume up and down. lots of clicks

very difficult to make live volume adjustments in ambient style music as the clicks really stand out.

### Other important information

* How often does this bug happen? (every time, often, "it only happened once")

* Does this bug happen in previous firmware versions?
do not know, I installed 1.3.1 as soon as I got the device.
* Does this bug happen in every project?
have verified on the projects that came with the device (eg as noted above, on Starkey - First Explorer ). as well as my own.

**Comment by MortalJS** [comment]
Hi @gordwithers 
Can you check if the problem occurs in firmware 1.5?

**Comment by MortalJS** [comment]
No response. Closed
