### ISSUE TITLE
[1.3.1] Song Export does not follow the Song Slot configuration

### ISSUE THREAD

**Issue by gordwithers** [polyend/TrackerBetaTesting#994]
### Steps to reproduce

I have created a song that does the following:
1. Pattern 3
2. Pattern 1
3. Pattern 5
4. Pattern 5
5. Pattern 2
6. Pattern 6

When I hit "Play Song" it works as normal.
When I export the song, it exports 
1. Pattern 3
2. Pattern 1
3. Pattern 3 (should be 5)
4. Pattern 5
5. Pattern 2
6. Pattern 6

**Comment by MortalJS** [comment]
Hi @gordwithers 
Can you check if the problem occurs in firmware 1.5?

**Comment by MortalJS** [comment]
No response. Closed
